### ISSUE TITLE
Crash on start after building with GCC 11.0.0

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#10332]
### Steps to reproduce
1. Build with GCC 11.0.0 and `-D_GLIBCXX_ASSERTIONS`.
2. 
3. 

### Expected behaviour
Successful start.

### Actual behaviour
Crash:
```c++
#0  0x00007ffff358f292 in raise () at /lib64/libc.so.6
#1  0x00007ffff35788a4 in abort () at /lib64/libc.so.6
#2  0x0000555555a31cf8 in std::__replacement_assert(char const*, int, char const*, char const*) () at /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h:2648
#3  0x0000555556b8072f in std::_Optional_base_impl<Window::Notifications::ManagerType, std::_Optional_base<Window::Notifications::ManagerType, true, true> >::_M_get() ()
    at /usr/include/c++/11/optional:440
#4  std::_Optional_base_impl<Window::Notifications::ManagerType, std::_Optional_base<Window::Notifications::ManagerType, true, true> >::_M_get() ()
    at /usr/include/c++/11/optional:438
#5  std::optional<Window::Notifications::ManagerType>::operator*() && () at /usr/include/c++/11/optional:931
#6  operator()() () at ../Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp:715
#7  0x0000555556b8089d in Platform::Notifications::Create(Window::Notifications::System*) () at ../Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp:729
#8  0x0000555556994cf7 in operator() () at ../Telegram/SourceFiles/main/main_domain.cpp:37
#9  callable_invoke<Main::Domain::Domain(const QString&)::<lambda()>, Main::Account*> () at ../Telegram/lib_rpl/rpl/details/callable.h:105
#10 put_next() () at ../Telegram/lib_rpl/rpl/consumer.h:146
#11 0x000055555699e6fa in rpl::details::consumer_base<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >::handlers_put_next_copy(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/consumer.h:333
#12 rpl::details::consumer_base<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >::put_next_copy(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/consumer.h:383
#13 rpl::details::consumer_base<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >::put_next_forward(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/consumer.h:277
#14 rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}::operator()<Main::Account* const&>(Main::Account* const&) const ()
    at ../Telegram/lib_rpl/rpl/take.h:31
#15 rpl::details::callable_invoke<rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}, Main::Account* const&>(rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}&&, Main::Account* const&) () at ../Telegram/lib_rpl/rpl/details/callable.h:99
#16 rpl::details::const_ref_call_invoke<rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}, Main::Account*>(rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}&&, Main::Account* const&) () at ../Telegram/lib_rpl/rpl/details/callable.h:134
#17 rpl::details::consumer_handlers<Main::Account*, rpl::no_error, rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#1}, rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda(auto:1&&)#2}, rpl::details::take_helper::operator()<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>(rpl::producer<Main::Account*, rpl::no_error, rpl::event_stream<Main::Account*, rpl::no_error>::events() const::{lambda(auto:1 const&)#1}>&&)::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&)::{lambda()#3}>::put_next_copy(Main::Account* const&) () at ../Telegram/lib_rpl/rpl/consumer.h:167
#18 0x000055555699f4b8 in rpl::details::consumer_base<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >::handlers_put_next_copy(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/consumer.h:333
#19 rpl::details::consumer_base<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >::put_next_copy(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/consumer.h:383
#20 rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}::operator()<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > >(rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > const&) const () at ../Telegram/lib_rpl/rpl/event_stream.h:136
#21 __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}>::operator()<base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > > >(base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >) () at /usr/include/c++/11/bits/predefined_ops.h:316
#22 std::__find_if<base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}> >(base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}>, std::random_access_iterator_tag) () at /usr/include/c++/11/bits/stl_algobase.h:2069
#23 std::__find_if<base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}> >(base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}>) () at /usr/include/c++/11/bits/stl_algobase.h:2114
#24 std::__remove_if<base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}> >(base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, __gnu_cxx::__ops::_Iter_pred<rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}>) () at /usr/include/c++/11/bits/stl_algo.h:816
#25 std::remove_if<base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}>(base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, base::index_based_iterator<std::vector<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> >, std::allocator<rpl::consumer<Main::Account*, rpl::no_error, rpl::details::type_erased_handlers<Main::Account*, rpl::no_error> > > > >, rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const::{lambda(auto:1 const&)#1}) ()
    at /usr/include/c++/11/bits/stl_algo.h:894
#26 rpl::event_stream<Main::Account*, rpl::no_error>::fire_forward<Main::Account* const&>(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/event_stream.h:135
#27 0x000055555699a2cd in rpl::event_stream<Main::Account*, rpl::no_error>::fire_copy(Main::Account* const&) const () at ../Telegram/lib_rpl/rpl/event_stream.h:35
#28 rpl::variable<Main::Account*, rpl::no_error>::assign<Main::Account*>(Main::Account*&&) () at ../Telegram/lib_rpl/rpl/variable.h:143
#29 rpl::variable<Main::Account*, rpl::no_error>::operator=<Main::Account*, void>(Main::Account*&&) () at ../Telegram/lib_rpl/rpl/variable.h:61
#30 Main::Domain::activate(gsl::not_null<Main::Account*>) () at ../Telegram/SourceFiles/main/main_domain.cpp:412
#31 0x000055555699b751 in Main::Domain::activateAfterStarting() () at ../Telegram/SourceFiles/main/main_domain.cpp:135
#32 0x000055555699b814 in Main::Domain::start(QByteArray const&) () at ../Telegram/SourceFiles/main/main_domain.cpp:67
#33 0x000055555633623f in Core::Application::startDomain() () at ../Telegram/SourceFiles/core/application.cpp:287
#34 0x0000555556339ac8 in Core::Application::run() () at ../Telegram/SourceFiles/core/application.cpp:264
#35 0x000055555637915a in std::function<void ()>::operator()() const () at /usr/include/c++/11/bits/std_function.h:560
#36 base::unique_function<void ()>::operator()() () at ../Telegram/lib_base/base/unique_function.h:127
#37 base::InvokeQueuedEvent::invoke() () at ../Telegram/lib_base/base/invoke_queued.h:26
#38 Core::Sandbox::notifyOrInvoke(QObject*, QEvent*) () at ../Telegram/SourceFiles/core/sandbox.cpp:526
#39 0x0000555556379237 in Core::Sandbox::notify(QObject*, QEvent*) () at ../Telegram/SourceFiles/core/sandbox.cpp:545
#40 0x00007ffff3d1df48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#41 0x00007ffff3d20c76 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#42 0x00007ffff3d6ac57 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#43 0x00007ffff50160bf in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#44 0x00007ffff5069358 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#45 0x00007ffff50139b3 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#46 0x00007ffff3d6a6f8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#47 0x00007ffff3d1c9b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#48 0x00007ffff3d24544 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#49 0x0000555556377f0f in Core::Sandbox::start() () at ../Telegram/SourceFiles/core/sandbox.cpp:157
#50 0x000055555636c865 in Core::Launcher::executeApplication() () at ../Telegram/SourceFiles/core/launcher.cpp:526
#51 0x000055555636ca8d in Core::Launcher::exec() () at ../Telegram/SourceFiles/core/launcher.cpp:348
#52 0x0000555555a12d39 in main() () at ../Telegram/SourceFiles/main.cpp:12
```

### Configuration
**Operating system:** Fedora 34

**Version of Telegram Desktop:** 2.5.8 and latest dev too.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: build from sources.

**Used theme**: n/a

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Remove all additional hardening flags on tdesktop & tg_owt build

**Comment by xvitaly** [comment]
> Remove all additional hardening flags on tdesktop & tg_owt build

I cannot. Please fix your code. Array/Vector out of bounds is a potential vulnerability.

**Comment by ilya-fedin** [comment]
> Array/Vector out of bounds is a potential vulnerability.

I don't see arrays or vectors in the trace. I also don't see actual error message in the trace.

**Comment by xvitaly** [comment]
Confirmed on GCC 10.2.1 too.

**Comment by xvitaly** [comment]
> I don't see arrays or vectors in the trace. I also don't see actual error message in the trace.

Crash related to [notifications_manager_linux.cpp](https://github.com/telegramdesktop/tdesktop/blob/v2.5.8/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L708).

**Comment by ilya-fedin** [comment]
> Crash related to [notifications_manager_linux.cpp](https://github.com/telegramdesktop/tdesktop/blob/v2.5.8/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L708).

You provided only trace, while actual error should be in stderr

**Comment by xvitaly** [comment]
The same crash confirmed by Fedora 32 user on openbox.

**Comment by xvitaly** [comment]
> You provided only trace, while actual error should be in stderr

Stderr:

```
/usr/include/c++/10/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = Window::Notifications::ManagerType; _Dp = std::_Optional_base<Window::Notifications::ManagerType, true, true>]: Assertion 'this->_M_is_engaged()' failed.
Aborted (core dumped)
```

**Comment by john-preston** [comment]
@xvitaly Should be fixed by #10336.

**Comment by olegon-ru** [comment]
Openbox / Fedora 33
Source       : telegram-desktop-2.5.8-1.fc33.src.rpm
Crash immediately after start with upgraded and clean profile :(
/usr/include/c++/10/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = Window::Notifications::ManagerType; _Dp = std::_Optional_base<Window::Notifications::ManagerType, true, true>]: Assertion 'this->_M_is_engaged()' failed.
Aborted (core dumped)

**Comment by xvitaly** [comment]
@john-preston @ilya-fedin Fixed. Thanks.
