### ISSUE TITLE
Segfault on displayPhoto

### ISSUE THREAD

**Issue by ffix** [telegramdesktop/tdesktop#1132]
Just got segfault on displayPhoto.

Traceback:
```
(gdb) bt
#0  0x0000000000e30ef0 in QScreen::handle() const ()
#1  0x0000000000e0c36e in QWindow::setVisible(bool) ()
#2  0x0000000000a056d8 in QWidgetPrivate::show_sys() ()
#3  0x0000000000a0f002 in QWidgetPrivate::show_helper() ()
#4  0x0000000000a12455 in QWidget::setVisible(bool) ()
#5  0x0000000000605d53 in MediaView::displayPhoto (this=0x2fd3160, photo=0x449a0b0, item=0x3144470) at ../../Telegram/SourceFiles/mediaview.cpp:810
#6  0x0000000000605153 in MediaView::showPhoto (this=0x2fd3160, photo=0x449a0b0, context=0x3144470) at ../../Telegram/SourceFiles/mediaview.cpp:677
#7  0x00000000006fdc1f in Window::showPhoto (this=0x260f6b0, photo=0x449a0b0, item=0x3144470) at ../../Telegram/SourceFiles/window.cpp:751
#8  0x00000000006fdbd4 in Window::showPhoto (this=0x260f6b0, lnk=0x42e4b30, item=0x3144470) at ../../Telegram/SourceFiles/window.cpp:746
#9  0x00000000006db2fe in PhotoLink::onClick (this=0x42e4b30, button=Qt::LeftButton) at ../../Telegram/SourceFiles/structs.cpp:522
#10 0x00000000005a8ff3 in HistoryList::dragActionFinish (this=0x31d3f90, screenPos=..., button=Qt::LeftButton) at ../../Telegram/SourceFiles/historywidget.cpp:666
#11 0x00000000005a9816 in HistoryList::mouseReleaseEvent (this=0x31d3f90, e=0x7fffffffd5a0) at ../../Telegram/SourceFiles/historywidget.cpp:716
#12 0x0000000000a12b50 in QWidget::event(QEvent*) ()
#13 0x00000000005a5ade in HistoryList::event (this=0x31d3f90, e=0x7fffffffd5a0) at ../../Telegram/SourceFiles/historywidget.cpp:185
#14 0x00000000009e3cdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#15 0x00000000009e9979 in QApplication::notify(QObject*, QEvent*) ()
#16 0x00000000014382d3 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
#17 0x00000000009e8879 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
#18 0x0000000000a2b58b in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#19 0x0000000000a2db3b in QWidgetWindow::event(QEvent*) ()
#20 0x00000000009e3cdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#21 0x00000000009e9276 in QApplication::notify(QObject*, QEvent*) ()
#22 0x00000000014382d3 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
#23 0x0000000000e02b30 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#24 0x0000000000e04895 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
#25 0x0000000000deaeba in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#26 0x0000000000d7fef0 in userEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
#27 0x00007fffef1a99fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#28 0x00007fffef1a9ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#29 0x00007fffef1a9d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#30 0x000000000148dedf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#31 0x0000000001435a61 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#32 0x000000000143de1b in QCoreApplication::exec() ()
#33 0x000000000043be36 in main (argc=1, argv=0x7fffffffe1b8) at ../../Telegram/SourceFiles/main.cpp:76
```

I'm using Telegrem 0.9.1 (debug build) on ArchLinux.

**Comment by auchri** [comment]
Does it also happen on 0.9.2?

**Comment by ffix** [comment]
Haven't tested 0.9.2 yet (looks like it was released few hours ago). I'll try.

**Comment by ffix** [comment]
Can't reproduce it anymore with v0.9.2 or v0.9.1.
Looks like it is occasional.
