### ISSUE TITLE
Segfault on quit Telegram.

### ISSUE THREAD

**Issue by ffix** [telegramdesktop/tdesktop#1133]
I can reproduce it in 90% on my system (ArchLinux/Cinnamon DE).
Telegram v.0.9.2 (and v.0.9.1 too) just segfaulting if I click "Quit Telegram" in menu.

Backtrace:

```
RUN

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe5cff700 (LWP 30170)]
[New Thread 0x7fffe4def700 (LWP 30171)]
[New Thread 0x7fffdfb0a700 (LWP 30172)]
[New Thread 0x7fffde334700 (LWP 30173)]
[Thread 0x7fffde334700 (LWP 30173) exited]
[New Thread 0x7fffde334700 (LWP 30174)]
[Thread 0x7fffde334700 (LWP 30174) exited]
[New Thread 0x7fffde334700 (LWP 30175)]
[Thread 0x7fffde334700 (LWP 30175) exited]
[New Thread 0x7fffde334700 (LWP 30176)]
[New Thread 0x7fffe4105700 (LWP 30177)]
[New Thread 0x7fffdcb36700 (LWP 30178)]
[New Thread 0x7fffc7ffe700 (LWP 30179)]
[Thread 0x7fffe4105700 (LWP 30177) exited]
[New Thread 0x7fffc77fd700 (LWP 30184)]
[New Thread 0x7fffc6ffc700 (LWP 30187)]
[New Thread 0x7fffc67fb700 (LWP 30188)]
[Thread 0x7fffc6ffc700 (LWP 30187) exited]
[Thread 0x7fffc67fb700 (LWP 30188) exited]
[Thread 0x7fffc7ffe700 (LWP 30179) exited]
[Thread 0x7fffdcb36700 (LWP 30178) exited]
[Thread 0x7fffc77fd700 (LWP 30184) exited]
[Thread 0x7fffdfb0a700 (LWP 30172) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffeed43660 in pthread_join () from /usr/lib/libpthread.so.0


BACKTRACE FULL

#0  0x00007fffeed43660 in pthread_join () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00007ffff705b350 in ?? () from /usr/lib/libopenal.so.1
No symbol table info available.
#2  0x00007ffff70582d4 in ?? () from /usr/lib/libopenal.so.1
No symbol table info available.
#3  0x00007ffff70385cd in alcDestroyContext () from /usr/lib/libopenal.so.1
No symbol table info available.
#4  0x00000000004eba8f in audioFinish () at ../../Telegram/SourceFiles/audio.cpp:256
No locals.
#5  0x000000000049ea73 in App::deinitMedia (completely=true) at ../../Telegram/SourceFiles/app.cpp:1959
No locals.
#6  0x00000000004ca063 in Application::~Application (this=0x7fffffffddf0, __in_chrg=<optimized out>) at ../../Telegram/SourceFiles/application.cpp:859
No locals.
#7  0x000000000043bf34 in main (argc=1, argv=0x7fffffffe1b8) at ../../Telegram/SourceFiles/main.cpp:77
        a_cnt = 1
        a_argv = {0x7fffffffe5a2 "/usr/bin/telegram-desktop", 0x0}
        app = {<PsApplication> = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x24e9fe0 <QApplication::staticMetaObject>, stringdata = 0x1d1a4c0 <qt_meta_stringdata_PsApplication>, data = 0x1d1a500 <qt_meta_data_PsApplication>, static_metacall = 0x9994d0 <PsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}}, <RPCSender> = {_rpcDoneHandlers = {q_hash = {{d = 0x1e5d620 <QHashData::shared_null>, e = 0x1e5d620 <QHashData::shared_null>}}}, _rpcFailHandlers = {q_hash = {{d = 0x1e5d620 <QHashData::shared_null>, e = 0x1e5d620 <QHashData::shared_null>}}}}, static staticMetaObject = {d = {superdata = 0x24d70c0 <PsApplication::staticMetaObject>, stringdata = 0x1d1b9e0 <qt_meta_stringdata_Application>, data = 0x1d1be40 <qt_meta_data_Application>, static_metacall = 0x999cb2 <Application::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, photoUpdates = {d = 0x1e9d620 <QMapDataBase::shared_null>}, killDownloadSessionTimes = {d = 0x1e9d620 <QMapDataBase::shared_null>}, killDownloadSessionsTimer = {<QTimer> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x251f5a0 <QTimer::staticMetaObject>, stringdata = 0x1d339c0 <qt_meta_stringdata_SingleTimer>, data = 0x1d33a80 <qt_meta_data_SingleTimer>, static_metacall = 0x9a7ffa <SingleTimer::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, _finishing = 0, _inited = false}, serverName = {static null = {<No data fields>}, d = 0x25e5770}, socket = <incomplete type>, socketRead = {static null = {<No data fields>}, d = 0x1e5bd00 <QArrayData::shared_null>}, server = <incomplete type>, clients = {d = 0x1e5bd00 <QArrayData::shared_null>}, closing = false, lastActionTime = 8589926064, window = 0x267acd0, writeUserConfigTimer = <incomplete type>, _translator = 0x25f4f60}
        args = {{static MaxSize = 1073741800, d = 0x25b6660}}
        a_argc = 1
        _init = {<No data fields>}
        result = 0


INFO REGISTERS

rax            0x0  0
rbx            0x7fffffffdce4   140737488346340
rcx            0x0  0
rdx            0x7fffee49fb98   140737191213976
rsi            0x7fffffffdcc0   140737488346304
rdi            0x7fffe4105700   140737019664128
rbp            0x2a5d560    0x2a5d560
rsp            0x7fffffffdcb8   0x7fffffffdcb8
r8             0x2a5ce80    44420736
r9             0x0  0
r10            0x10d    269
r11            0x7ffff7038570   140737337591152
r12            0x0  0
r13            0x7fffffffe1b0   140737488347568
r14            0x0  0
r15            0x0  0
rip            0x7fffeed43660   0x7fffeed43660 <pthread_join>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33 51
ss             0x2b 43
ds             0x0  0
es             0x0  0
fs             0x0  0
gs             0x0  0

THREAD APPLY ALL BACKTRACE

Thread 8 (Thread 0x7fffde334700 (LWP 30176)):
#0  0x00007fffee1e118d in poll () from /usr/lib/libc.so.6
#1  0x00007fffdf0ecf51 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007fffdf0de571 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007fffdf0dec0e in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007fffdf0decc0 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007fffdf0ecee6 in ?? () from /usr/lib/libpulse.so.0
#6  0x00007fffdee8d5b8 in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.0.so
#7  0x00007fffeed424a4 in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fffee1ea13d in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffe4def700 (LWP 30171)):
#0  0x00007fffee1e118d in poll () from /usr/lib/libc.so.6
#1  0x00007fffef1a9c7c in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007fffef1a9d8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x000000000148e35f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#4  0x0000000001435ee1 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#5  0x000000000128b5f4 in QThread::run() ()
#6  0x0000000001290e0e in QThreadPrivate::start(void*) ()
#7  0x00007fffeed424a4 in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fffee1ea13d in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe5cff700 (LWP 30170)):
#0  0x00007fffee1e118d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff3fadae2 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff3faf757 in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x0000000000d53259 in QXcbEventReader::run() ()
#4  0x0000000001290e0e in QThreadPrivate::start(void*) ()
#5  0x00007fffeed424a4 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fffee1ea13d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7faa840 (LWP 30166)):
#0  0x00007fffeed43660 in pthread_join () from /usr/lib/libpthread.so.0
#1  0x00007ffff705b350 in ?? () from /usr/lib/libopenal.so.1
#2  0x00007ffff70582d4 in ?? () from /usr/lib/libopenal.so.1
#3  0x00007ffff70385cd in alcDestroyContext () from /usr/lib/libopenal.so.1
#4  0x00000000004eba8f in audioFinish () at ../../Telegram/SourceFiles/audio.cpp:256
#5  0x000000000049ea73 in App::deinitMedia (completely=true) at ../../Telegram/SourceFiles/app.cpp:1959
#6  0x00000000004ca063 in Application::~Application (this=0x7fffffffddf0, __in_chrg=<optimized out>) at ../../Telegram/SourceFiles/application.cpp:859
#7  0x000000000043bf34 in main (argc=1, argv=0x7fffffffe1b8) at ../../Telegram/SourceFiles/main.cpp:77
```

libs:

```
    linux-vdso.so.1 (0x00007fff42270000)
    libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007fb249139000)
    libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007fb248ebf000)
    liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fb248c99000)
    libexif.so.12 => /usr/lib/libexif.so.12 (0x00007fb248a54000)
    libopenal.so.1 => /usr/lib/libopenal.so.1 (0x00007fb2487e3000)
    libavformat.so.56 => /usr/lib/libavformat.so.56 (0x00007fb2483e3000)
    libavcodec.so.56 => /usr/lib/libavcodec.so.56 (0x00007fb24704c000)
    libswresample.so.1 => /usr/lib/libswresample.so.1 (0x00007fb246e31000)
    libavutil.so.54 => /usr/lib/libavutil.so.54 (0x00007fb246bc3000)
    libopus.so.0 => /usr/lib/libopus.so.0 (0x00007fb246977000)
    libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007fb246726000)
    libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fb246514000)
    libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fb2461d2000)
    libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007fb245fd0000)
    libXi.so.6 => /usr/lib/libXi.so.6 (0x00007fb245dc0000)
    libSM.so.6 => /usr/lib/libSM.so.6 (0x00007fb245bb8000)
    libICE.so.6 => /usr/lib/libICE.so.6 (0x00007fb24599b000)
    libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fb245778000)
    libxkbcommon-x11.so.0 => /usr/lib/libxkbcommon-x11.so.0 (0x00007fb245570000)
    libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fb24532c000)
    libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fb245066000)
    libinput.so.10 => /usr/lib/libinput.so.10 (0x00007fb244e44000)
    libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007fb244c04000)
    libudev.so.1 => /usr/lib/libudev.so.1 (0x00007fb2497a9000)
    libmtdev.so.1 => /usr/lib/libmtdev.so.1 (0x00007fb2449fe000)
    libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007fb2447d7000)
    libjasper.so.1 => /usr/lib/libjasper.so.1 (0x00007fb24457d000)
    libmng.so.2 => /usr/lib/libmng.so.2 (0x00007fb24430b000)
    libtiff.so.5 => /usr/lib/libtiff.so.5 (0x00007fb244087000)
    libwebp.so.5 => /usr/lib/libwebp.so.5 (0x00007fb243e26000)
    libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fb243bcd000)
    libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fb243998000)
    libproxy.so.1 => /usr/lib/libproxy.so.1 (0x00007fb243774000)
    libz.so.1 => /usr/lib/libz.so.1 (0x00007fb24355e000)
    libicui18n.so.55 => /usr/lib/libicui18n.so.55 (0x00007fb2430f8000)
    libicuuc.so.55 => /usr/lib/libicuuc.so.55 (0x00007fb242d65000)
    libicudata.so.55 => /usr/lib/libicudata.so.55 (0x00007fb2412af000)
    libpcre16.so.0 => /usr/lib/libpcre16.so.0 (0x00007fb241049000)
    libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb240e45000)
    libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007fb240c43000)
    libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fb240935000)
    librt.so.1 => /usr/lib/librt.so.1 (0x00007fb24072d000)
    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb240510000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb24018e000)
    libm.so.6 => /usr/lib/libm.so.6 (0x00007fb23fe90000)
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb23fc7a000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007fb23f8d6000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fb2495b0000)
    libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fb23f644000)
    libssh.so.4 => /usr/lib/libssh.so.4 (0x00007fb23f3c8000)
    libmodplug.so.1 => /usr/lib/libmodplug.so.1 (0x00007fb23f03c000)
    libbluray.so.1 => /usr/lib/libbluray.so.1 (0x00007fb23edfa000)
    libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007fb23eac6000)
    libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fb23e8b6000)
    libva.so.1 => /usr/lib/libva.so.1 (0x00007fb23e69a000)
    libxvidcore.so.4 => /usr/lib/libxvidcore.so.4 (0x00007fb23e388000)
    libx265.so.59 => /usr/lib/libx265.so.59 (0x00007fb23ddcd000)
    libx264.so.148 => /usr/lib/libx264.so.148 (0x00007fb23da57000)
    libvpx.so.2 => /usr/lib/libvpx.so.2 (0x00007fb23d65d000)
    libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007fb23d3aa000)
    libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007fb23d17d000)
    libtheoraenc.so.1 => /usr/lib/libtheoraenc.so.1 (0x00007fb23cf3c000)
    libtheoradec.so.1 => /usr/lib/libtheoradec.so.1 (0x00007fb23cd23000)
    libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007fb23cb0a000)
    libschroedinger-1.0.so.0 => /usr/lib/libschroedinger-1.0.so.0 (0x00007fb23c841000)
    libopenjpeg.so.1 => /usr/lib/libopenjpeg.so.1 (0x00007fb23c618000)
    libopencore-amrwb.so.0 => /usr/lib/libopencore-amrwb.so.0 (0x00007fb23c404000)
    libopencore-amrnb.so.0 => /usr/lib/libopencore-amrnb.so.0 (0x00007fb23c1da000)
    libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007fb23bf63000)
    libgsm.so.1 => /usr/lib/libgsm.so.1 (0x00007fb23bd58000)
    libsoxr.so.0 => /usr/lib/libsoxr.so.0 (0x00007fb23bae1000)
    libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fb23b871000)
    libffi.so.6 => /usr/lib/libffi.so.6 (0x00007fb23b668000)
    libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007fb23b463000)
    libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fb23b25f000)
    libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fb23b059000)
    libxcb-xkb.so.1 => /usr/lib/libxcb-xkb.so.1 (0x00007fb23ae3d000)
    libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fb23ac13000)
    libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fb23a9b2000)
    libevdev.so.2 => /usr/lib/libevdev.so.2 (0x00007fb23a798000)
    libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fb23a581000)
    libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fb23a37d000)
    libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007fb23a178000)
    libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007fb239f70000)
    libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007fb239d66000)
    libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0x00007fb239b62000)
    libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007fb239954000)
    libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007fb239746000)
    libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007fb239534000)
    libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007fb239325000)
    liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x00007fb2390ca000)
    libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007fb238d65000)
    libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007fb238aff000)
    libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007fb2388ec000)
    libnettle.so.6 => /usr/lib/libnettle.so.6 (0x00007fb2386b4000)
    libhogweed.so.4 => /usr/lib/libhogweed.so.4 (0x00007fb238480000)
    libogg.so.0 => /usr/lib/libogg.so.0 (0x00007fb238279000)
    liborc-0.4.so.0 => /usr/lib/liborc-0.4.so.0 (0x00007fb237ff9000)
    libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fb237dd7000)
    libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fb237bab000)
    libattr.so.1 => /usr/lib/libattr.so.1 (0x00007fb2379a6000)
```

**Comment by HUMZZY** [comment]
whats this for
