### ISSUE TITLE
2.9.1 segfaults in pw_init after attempting to make a call

### ISSUE THREAD

**Issue by hgkjshegfskef** [telegramdesktop/tdesktop#16768]
I have followed instructions from [wiki](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md) and built a debug version of telegram 2.9.1. I did this to attempt bisecting #16733. However, I wasn't able to even reach that point, as the client segfaults after counterparty accepts the call. [gdb execution with full backtrace](https://github.com/telegramdesktop/tdesktop/files/6945464/bt_full.txt). A few top lines:

```
(gdb) bt full
#0  0x0000000000000000 in  ()
#1  0x000000000c3e207e in pw_init(int*, char***) (argc=0x0, argv=0x0)
    at /usr/src/Libraries/tg_owt/out/Debug/gen/pipewire_stubs.cc:69
#2  0x00007ffff00881e2 in _snd_pcm_pipewire_open () at /usr/lib/alsa-lib/libasound_module_pcm_pipewire.so
#3  0x00007fffecf65d0d in  () at /usr/lib/libasound.so.2
#4  0x00007fffecf663c0 in  () at /usr/lib/libasound.so.2
#5  0x00007fffecf68539 in snd_pcm_open () at /usr/lib/libasound.so.2
#6  0x000000000be2b0c1 in (anonymous namespace)::AlsaPlayback::open(char const*) ()
#7  0x000000000be00069 in alcOpenDevice ()
#8  0x000000000a28d656 in Media::Audio::(anonymous namespace)::CreatePlaybackDevice() ()
    at /usr/src/tdesktop/Telegram/SourceFiles/media/audio/media_audio.cpp:152
```

I figured there might be an issue trying to get access to the sound device, perhaps related to docker. Notice that I run telegram as sudo, otherwise it cannot write its log file (perhaps I shouldn't?), and that is because I have to run docker as sudo (perhaps I can chown recursively out/ and try again). I have masked the pipewire service on the machine, but the result is the same.

I have also noticed that the source code paths are external dependencies (all or only some) are wrong, so gdb cannot show the source code lines:
```
(gdb) frame 1
#1  0x000000000c3e207e in pw_init (argc=0x0, argv=0x0) at /usr/src/Libraries/tg_owt/out/Debug/gen/pipewire_stubs.cc:69
69	/usr/src/Libraries/tg_owt/out/Debug/gen/pipewire_stubs.cc: No such file or directory.
```
So, do your own judgement.

### Steps to reproduce
1. Run debug version of telegram in container.
2. Open any chat.
3. Attempt to make a non-video call.
4. Counterparty accepts the call.
5. Your client will immediately segfault.

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.9.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: custom build

**Comment by hgkjshegfskef** [comment]
Nevermind. As always, as soon as you do a bug report, the issue sorts itself out. I was able to establish an audio call. What I did: chowned the directory to my user, enabled back pipewire, launched telegram with user rights.

Perhaps the application should check if it's started from root and do something about it -- either fix capturing sound devices, or prohibit audio and video calls when telegram is started from root.
