### ISSUE TITLE
Telegram Desktop Crashes Randomly on Arch Linux

### ISSUE THREAD

**Issue by oMoMa** [telegramdesktop/tdesktop#16776]
### Steps to reproduce
1. Run Telegram Desktop
2. Wait for it to happen (you can even leave it open in the background)
3. After some random time, it crashes.

### Expected behavior
Tell us what should happen
It shouldn't crash

### Actual behavior
Tell us what happens instead
It crashes (even without doing anything, running in the background)

### Configuration
**Operating system:**
Operating System: Arch Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.8-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Version of Telegram Desktop:**
ver 2.9 (2.9.0-4 according to pacman)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Arch Linux community repository [link](https://archlinux.org/packages/community/x86_64/telegram-desktop/)

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
[2021.08.08 13:59:25] Launched version: 2009000, install beta: [FALSE], alpha: 0, debug mode: [TRUE]
[2021.08.08 13:59:25] Executable dir: /usr/bin/, name: telegram-desktop
[2021.08.08 13:59:25] Initial working dir: /home/mehrshad/
[2021.08.08 13:59:25] Working dir: /home/mehrshad/.local/share/TelegramDesktop/
[2021.08.08 13:59:25] Command line: /usr/bin/telegram-desktop --
[2021.08.08 13:59:25] Executable path before check: /usr/bin/telegram-desktop
[2021.08.08 13:59:25] Logs started
[2021.08.08 13:59:25] Launcher filename: telegramdesktop.desktop
[2021.08.08 13:59:25] Connecting local socket to /run/user/1000/e2a366f94731c9df33396f568ae0a223-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2021.08.08 13:59:25] Socket connect error 0, starting server and app...
[2021.08.08 13:59:25] Moved logging from '/home/mehrshad/.local/share/TelegramDesktop/log_start0.txt' to '/home/mehrshad/.local/share/TelegramDesktop/log.txt'!
[2021.08.08 13:59:25] Primary screen DPI: 96.1263
[2021.08.08 13:59:25] App Info: reading settings...
[2021.08.08 13:59:25] App Info: reading encrypted settings...
[2021.08.08 13:59:25] Lang Info: Loaded cached, keys: 3261
[2021.08.08 13:59:25] OpenAL Logging Level: 3
[2021.08.08 13:59:25] Audio Playback Devices: Starship/Matisse HD Audio Controller Analog Stereo
[2021.08.08 13:59:25] Audio Playback Default Device: Starship/Matisse HD Audio Controller Analog Stereo
[2021.08.08 13:59:25] Audio Capture Devices: Starship/Matisse HD Audio Controller Analog Stereo;Monitor of Starship/Matisse HD Audio Controller Analog Stereo
[2021.08.08 13:59:25] Audio Capture Default Device: Starship/Matisse HD Audio Controller Analog Stereo
[2021.08.08 13:59:25] Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
[2021.08.08 13:59:25] Xcb GLX gl-integration created
[2021.08.08 13:59:25] Xcb GLX gl-integration successfully initialized
[2021.08.08 13:59:25] Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync 
[2021.08.08 13:59:25] Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] Not using D-Bus global menu.
[2021.08.08 13:59:25] Using Unity launcher counter.
[2021.08.08 13:59:25] System tray available: [TRUE]
[2021.08.08 13:59:25] App Info: reading accounts info...
[2021.08.08 13:59:25] App Info: bad decrypt key, data not decrypted - incorrect password?
[2021.08.08 13:59:25] App Info: could not decrypt pass-protected key from info file, maybe bad password...
[2021.08.08 13:59:25] Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync 
[2021.08.08 13:59:25] Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] OpenGL Profile: Compatibility.
[2021.08.08 13:59:25] OpenGL Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.8-arch1-1, LLVM 12.0.1)
[2021.08.08 13:59:25] OpenGL Vendor: AMD
[2021.08.08 13:59:25] OpenGL Version: 4.6 (Compatibility Profile) Mesa 21.1.6
[2021.08.08 13:59:25] OpenGL Extensions: GL_ARB_texture_swizzle, GL_EXT_framebuffer_multisample, GL_NV_depth_clamp, GL_APPLE_packed_pixels, GL_SUN_multi_draw_arrays, GL_ARB_separate_shader_objects, GL_EXT_texture, GL_ARB_seamless_cube_map, GL_ARB_point_sprite, GL_ARB_clear_texture, GL_EXT_timer_query, GL_NV_shader_atomic_int64, GL_EXT_texture_sRGB_decode, GL_EXT_stencil_wrap, GL_EXT_texture_rectangle, GL_NV_alpha_to_coverage_dither_control, GL_ARB_sync, GL_ANGLE_texture_compression_dxt5, GL_NV_primitive_restart, GL_KHR_robustness, GL_ARB_shader_texture_image_samples, GL_ARB_compute_shader, GL_KHR_parallel_shader_compile, GL_EXT_separate_specular_color, GL_ARB_vertex_shader, GL_IBM_texture_mirrored_repeat, GL_ARB_framebuffer_object, GL_NV_light_max_exponent, GL_ARB_compatibility, GL_ARB_shader_image_size, GL_ARB_pixel_buffer_object, GL_ARB_draw_indirect, GL_EXT_stencil_two_side, GL_ARB_copy_buffer, GL_ARB_map_buffer_alignment, GL_MESA_shader_integer_functions, GL_SGIS_texture_edge_clamp, GL_ARB_gpu_shader5, GL_AMD_vertex_shader_layer, GL_ARB_shading_language_include, GL_EXT_EGL_sync, GL_ARB_conditional_render_inverted, GL_ARB_robust_buffer_access_behavior, GL_EXT_texture_env_dot3, GL_ARB_texture_border_clamp, GL_ARB_vertex_type_10f_11f_11f_rev, GL_EXT_texture_sRGB_R8, GL_KHR_no_error, GL_ARB_texture_barrier, GL_KHR_robust_buffer_access_behavior, GL_ATI_blend_equation_separate, GL_ARB_viewport_array, GL_ARB_pipeline_statistics_query, GL_ARB_sampler_objects, GL_EXT_texture_shadow_lod, GL_ARB_shader_precision, GL_ATI_texture_mirror_once, GL_ARB_shader_atomic_counters, GL_EXT_framebuffer_sRGB, GL_ARB_framebuffer_no_attachments, GL_ARB_texture_rg, GL_MESA_framebuffer_flip_y, GL_ARB_shader_storage_buffer_object, GL_ARB_clear_buffer_object, GL_EXT_gpu_program_parameters, GL_ARB_texture_env_combine, GL_ARB_multisample, GL_ARB_parallel_shader_compile, GL_AMD_pinned_memory, GL_ARB_clip_control, GL_EXT_texture_compression_rgtc, GL_EXT_texture_compression_latc, GL_ARB_stencil_texturing, GL_EXT_pixel_buffer_object, GL_ARB_cull_distance, GL_ARB_shading_language_100, GL_ARB_shading_language_420pack, GL_ARB_transpose_matrix, GL_ARB_fragment_shader, GL_ARB_gpu_shader_int64, GL_ARB_shader_viewport_layer_array, GL_ARB_transform_feedback_instanced, GL_NV_copy_image, GL_AMD_query_buffer_object, GL_ARB_buffer_storage, GL_EXT_texture_integer, GL_ARB_texture_compression_bptc, GL_ARB_fragment_program_shadow, GL_ATI_fragment_shader, GL_KHR_texture_compression_astc_ldr, GL_NV_texture_rectangle, GL_ARB_timer_query, GL_EXT_provoking_vertex, GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_get_program_binary, GL_ARB_transform_feedback3, GL_ARB_occlusion_query2, GL_ARB_get_texture_sub_image, GL_ARB_texture_view, GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_shader_draw_parameters, GL_EXT_multi_draw_arrays, GL_EXT_window_rectangles, GL_KHR_texture_compression_astc_sliced_3d, GL_ARB_ES2_compatibility, GL_ARB_draw_buffers_blend, GL_ARB_depth_buffer_float, GL_EXT_packed_float, GL_ARB_texture_query_levels, GL_EXT_texture_filter_anisotropic, GL_EXT_shader_samples_identical, GL_EXT_texture_sRGB, GL_EXT_texture_buffer_object, GL_ARB_base_instance, GL_ARB_gpu_shader_fp64, GL_ARB_depth_texture, GL_ARB_texture_storage, GL_EXT_shader_integer_mix, GL_ARB_texture_buffer_range, GL_EXT_texture_lod_bias, GL_ARB_transform_feedback2, GL_EXT_blend_equation_separate, GL_ARB_internalformat_query2, GL_ARB_arrays_of_arrays, GL_ATI_texture_compression_3dc, GL_IBM_multimode_draw_arrays, GL_ARB_bindless_texture, GL_SGIS_generate_mipmap, GL_EXT_transform_feedback, GL_AMD_multi_draw_indirect, GL_ARB_copy_image, GL_ARB_ES3_1_compatibility, GL_ARB_enhanced_layouts, GL_NV_packed_depth_stencil, GL_ARB_texture_cube_map, GL_ARB_explicit_uniform_location, GL_NVX_gpu_memory_info, GL_EXT_blend_subtract, GL_KHR_debug, GL_AMD_seamless_cubemap_per_texture, GL_ATI_separate_stencil, GL_ARB_texture_query_lod, GL_ARB_point_parameters, GL_ARB_explicit_attrib_location, GL_ARB_shader_clock, GL_EXT_EGL_image_storage, GL_EXT_texture_env_add, GL_EXT_secondary_color, GL_ARB_compressed_texture_pixel_storage, GL_EXT_texture_snorm, GL_NV_texgen_reflection, GL_ARB_shader_texture_lod, GL_EXT_point_parameters, GL_EXT_depth_bounds_test, GL_EXT_gpu_shader4, GL_ARB_texture_stencil8, GL_NV_compute_shader_derivatives, GL_ARB_draw_instanced, GL_EXT_blend_minmax, GL_AMD_shader_trinary_minmax, GL_ARB_draw_elements_base_vertex, GL_EXT_memory_object_fd, GL_NV_half_float, GL_AMD_conservative_depth, GL_ARB_multi_bind, GL_EXT_draw_buffers2, GL_EXT_vertex_attrib_64bit, GL_ARB_color_buffer_float, GL_EXT_shadow_funcs, GL_EXT_semaphore, GL_MESA_texture_signed_rgba, GL_AMD_vertex_shader_viewport_index, GL_EXT_demote_to_helper_invocation, GL_ARB_shading_language_packing, GL_INTEL_blackhole_render, GL_EXT_abgr, GL_EXT_texture_env_combine, GL_EXT_draw_instanced, GL_EXT_copy_texture, GL_ARB_shader_subroutine, GL_EXT_blend_color, GL_ARB_half_float_pixel, GL_OES_read_format, GL_EXT_packed_pixels, GL_ARB_direct_state_access, GL_ARB_texture_filter_anisotropic, GL_ARB_derivative_control, GL_EXT_texture_edge_clamp, GL_ARB_vertex_array_object, GL_ARB_texture_buffer_object, GL_ARB_texture_compression_rgtc, GL_ARB_texture_env_add, GL_ARB_robustness, GL_ARB_seamless_cubemap_per_texture, GL_ARB_query_buffer_object, GL_EXT_shader_image_load_formatted, GL_ARB_fragment_layer_viewport, GL_ARB_shader_bit_encoding, GL_EXT_direct_state_access, GL_ATI_draw_buffers, GL_EXT_packed_depth_stencil, GL_ARB_shader_atomic_counter_ops, GL_ARB_multi_draw_indirect, GL_EXT_texture_array, GL_ARB_vertex_attrib_binding, GL_EXT_framebuffer_blit, GL_ARB_texture_non_power_of_two, GL_ARB_shader_image_load_store, GL_EXT_polygon_offset_clamp, GL_IBM_rasterpos_clip, GL_ARB_vertex_program, GL_EXT_shader_image_load_store, GL_EXT_texture_object, GL_ARB_transform_feedback_overflow_query, GL_NV_texture_env_combine4, GL_ARB_internalformat_query, GL_ARB_texture_storage_multisample, GL_ARB_invalidate_subdata, GL_ARB_multitexture, GL_ATI_texture_env_combine3, GL_MESA_window_pos, GL_ARB_texture_env_crossbar, GL_ARB_window_pos, GL_EXT_texture_swizzle, GL_ARB_conservative_depth, GL_EXT_blend_func_separate, GL_ARB_tessellation_shader, GL_EXT_draw_range_elements, GL_ARB_fragment_program, GL_ARB_texture_mirrored_repeat, GL_ARB_compute_variable_group_size, GL_ARB_spirv_extensions, GL_ARB_shader_group_vote, GL_EXT_rescale_normal, GL_AMD_draw_buffers_blend, GL_AMD_shader_stencil_export, GL_ARB_provoking_vertex, GL_ARB_texture_float, GL_EXT_texture_shared_exponent, GL_ATI_texture_float, GL_ARB_texture_gather, GL_NV_fog_distance, GL_EXT_semaphore_fd, GL_AMD_depth_clamp_separate, GL_ARB_program_interface_query, GL_ARB_shader_objects, GL_ARB_uniform_buffer_object, GL_SGIS_texture_border_clamp, GL_ARB_texture_multisample, GL_EXT_subtexture, GL_ARB_shader_stencil_export, GL_ARB_fragment_coord_conventions, GL_ARB_framebuffer_sRGB, GL_KHR_blend_equation_advanced, GL_ARB_texture_env_dot3, GL_ANGLE_texture_compression_dxt3, GL_ARB_depth_clamp, GL_NV_conditional_render, GL_EXT_texture_cube_map, GL_ARB_sample_shading, GL_INGR_blend_func_separate, GL_ARB_vertex_attrib_64bit, GL_EXT_fog_coord, GL_ARB_vertex_buffer_object, GL_KHR_context_flush_control, GL_OES_EGL_image, GL_ARB_map_buffer_range, GL_ARB_indirect_parameters, GL_NV_vdpau_interop, GL_ARB_texture_buffer_object_rgb32, GL_NV_blend_square, GL_ARB_texture_cube_map_array, GL_NV_copy_depth_to_color, GL_ARB_occlusion_query, GL_S3_s3tc, GL_EXT_texture_compression_dxt1, GL_SGIS_texture_lod, GL_AMD_framebuffer_multisample_advanced, GL_ARB_shadow, GL_NV_texture_barrier, GL_ARB_vertex_array_bgra, GL_AMD_texture_texture4, GL_ARB_ES3_compatibility, GL_ARB_blend_func_extended, GL_EXT_texture3D, GL_EXT_framebuffer_multisample_blit_scaled, GL_ARB_shader_ballot, GL_ARB_texture_rgb10_a2ui, GL_EXT_vertex_array_bgra, GL_AMD_performance_monitor, GL_ARB_draw_buffers, GL_EXT_texture_compression_s3tc, GL_ARB_texture_rectangle, GL_EXT_framebuffer_object, GL_MESA_pack_invert, GL_ARB_instanced_arrays, GL_ARB_texture_compression, GL_ARB_polygon_offset_clamp, GL_EXT_texture_mirror_clamp, GL_EXT_compiled_vertex_array, GL_EXT_bgra, GL_EXT_vertex_array, GL_ARB_debug_output, GL_ATI_meminfo, GL_ARB_half_float_vertex, GL_ARB_gl_spirv, GL_EXT_memory_object
[2021.08.08 13:59:25] OpenGL: QOpenGLContext created, version: 4.4.
[2021.08.08 13:59:25] OpenGL: [TRUE] (OverlayWidget)
[2021.08.08 13:59:25] Requested format before FBConfig/Visual selection: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] Available GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync 
[2021.08.08 13:59:25] Got format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
[2021.08.08 13:59:25] Using SNI tray icon.
[2021.08.08 13:59:27] App Info: reading accounts info...
[2021.08.08 13:59:27] App Info: reading encrypted info...
[2021.08.08 13:59:27] App Info: reading map...
[2021.08.08 13:59:27] App Info: reading encrypted map...
[2021.08.08 13:59:27] App Info: reading encrypted user settings...
[2021.08.08 13:59:27] App Info: encrypted user settings read.
[2021.08.08 13:59:27] App Info: reading encrypted mtp data...
[2021.08.08 13:59:27] MTP Info: read keys, current: 5, to destroy: 0
[2021.08.08 13:59:27] Map read time: 1
[2021.08.08 13:59:27] App Info: reading encrypted mtp config...
[2021.08.08 13:59:27] App Info: reading map...
[2021.08.08 13:59:27] App Info: reading encrypted map...
[2021.08.08 13:59:27] HTTP Error: host not found - Host 2001:67c:4e8:f004::a not found
[2021.08.08 13:59:27] App Info: reading encrypted user settings...
[2021.08.08 13:59:27] App Info: encrypted user settings read.
[2021.08.08 13:59:27] App Info: reading encrypted mtp data...
[2021.08.08 13:59:27] MTP Info: read keys, current: 5, to destroy: 0
[2021.08.08 13:59:27] Map read time: 0
[2021.08.08 13:59:27] App Info: reading encrypted mtp config...
[2021.08.08 13:59:27] HTTP Error: host not found - Host 2001:b28:f23d:f001::a not found
[2021.08.08 13:59:27] Export Info: Destroy top bar by controller removal.
[2021.08.08 13:59:27] Error while inflating gzip file: SVG format check failed
[2021.08.08 13:59:27] Notification daemon product name: Plasma
[2021.08.08 13:59:27] Notification daemon vendor name: KDE
[2021.08.08 13:59:27] Notification daemon version: 5.22.4
[2021.08.08 13:59:27] Notification daemon specification version: 1.2
[2021.08.08 13:59:27] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, persistence, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[2021.08.08 13:59:30] HTTP Error: host not found - Host 2001:67c:4e8:f002::a not found
[2021.08.08 13:59:32]   OpenType support missing for "Open Sans", script 11
[2021.08.08 14:00:14] API Warning: not loaded minimal channel applied.
[2021.08.08 14:00:14] API Warning: not loaded minimal channel applied.
[2021.08.08 14:01:08]   OpenType support missing for "Open Sans", script 20
[2021.08.08 14:02:38] HTTP Error: host not found - Host 2001:b28:f23f:f005::a not found
[2021.08.08 14:03:00] HTTP Error: host not found - Host 2001:67c:4e8:f004::a not found
[2021.08.08 14:03:29] Audio Info: recreating audio device and reattaching the tracks
</details>

**Comment by oMoMa** [comment]
I have enabled debugmode. I can share the extra generated logs if needed.

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by alkaris2** [comment]
Also have same issue on Manjaro, Telegram will randomly crash. Same issue still occurs even if download pre-packaged versions like Flatpak, Snap, etc.. from https://desktop.telegram.org

**Comment by Aokromes** [comment]
i suggest you to run telegram under gdb to get proper crashlogs.

**Comment by oMoMa** [comment]
> plz try downloading official version from https://desktop.telegram.org

Thanks. It seems to be ok for now. Will report if anything unexpected happens.
So the problem is related to Arch package maintainer then?

**Comment by Thermi** [comment]
Right after start
```
Thread 1 "telegram-deskto" received signal SIGABRT, Aborted.                                                                       [14/143]
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x00007FFFE296B9C0  RBP: 0x00007FFFF2B358F0  RSP: 0x00007FFFFFFFC7E0  o d I t s Z a P c 
  RDI: 0x0000000000000002  RSI: 0x00007FFFFFFFC7E0  RDX: 0x0000000000000000  RCX: 0x00007FFFF29AFD22  RIP: 0x00007FFFF29AFD22
  R8 : 0x0000000000000000  R9 : 0x00007FFFFFFFC7E0  R10: 0x0000000000000008  R11: 0x0000000000000246  R12: 0x00007FFFFFFFCA70
  R13: 0x0000000000001000  R14: 0x0000000000000020  R15: 0x00007FFFDF800000
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff29afd22 <raise+322>:  mov    rax,QWORD PTR [rsp+0x108]
   0x7ffff29afd2a <raise+330>:  sub    rax,QWORD PTR fs:0x28
   0x7ffff29afd33 <raise+339>:  jne    0x7ffff29afd54 <raise+372>
   0x7ffff29afd35 <raise+341>:  mov    eax,r8d
   0x7ffff29afd38 <raise+344>:  add    rsp,0x118
   0x7ffff29afd3f <raise+351>:  ret    
   0x7ffff29afd40 <raise+352>:  mov    rdx,QWORD PTR [rip+0x183109]        # 0x7ffff2b32e50
   0x7ffff29afd47 <raise+359>:  neg    eax
-----------------------------------------------------------------------------------------------------------------------------
0x00007ffff29afd22 in raise () from /usr/lib/libc.so.6
gdb$ bt full
#0  0x00007ffff29afd22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff2999862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff29f1d28 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff2a80cca in __fortify_fail () at /usr/lib/libc.so.6
#4  0x00007ffff2a80c94 in  () at /usr/lib/libc.so.6
#5  0x00007ffff459ad61 in  () at /usr/lib/libjemalloc.so.2
#6  0x00007ffff4555462 in  () at /usr/lib/libjemalloc.so.2
#7  0x00007ffff384a7d3 in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) () at /us
r/lib/libQt5Core.so.5
#8  0x00007fffe0eeebd3 in  () at /usr/lib/libQt5XcbQpa.so.5
#9  0x00007fffe0ef954d in  () at /usr/lib/libQt5XcbQpa.so.5
#10 0x00007fffe0f0a7a4 in QXcbWindow::setWindowIcon(QIcon const&) () at /usr/lib/libQt5XcbQpa.so.5
#11 0x00007ffff3e0f0c4 in QWindow::setIcon(QIcon const&) () at /usr/lib/libQt5Gui.so.5
#12 0x00007ffff30cc7b9 in QWidgetPrivate::setWindowIcon_sys() () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff30d7437 in QWidget::create(unsigned long long, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#14 0x00005555570537d9 in  ()
#15 0x00005555567d0d2c in  ()
#16 0x000055555682840a in  ()
#17 0x000055555682870f in  ()
#18 0x00007ffff3a2a3aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff3a2d4a9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#20 0x00007ffff3a839a4 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007ffff48b010c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff4903b99 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff48ad871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff3a82fd6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff3a28d1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#26 0x00007ffff3a31284 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#27 0x0000555556827010 in  ()
#28 0x0000555556814b4f in  ()
#29 0x0000555556814e0f in  ()
#30 0x0000555555b55376 in  ()
#31 0x00007ffff299ab25 in __libc_start_main () at /usr/lib/libc.so.6
#32 0x0000555555b5f82e in  ()
quit 

```

**Comment by Aokromes** [comment]
> > plz try downloading official version from [desktop.telegram.org](https://desktop.telegram.org)
> 
> Thanks. It seems to be ok for now. Will report if anything unexpected happens.
> So the problem is related to Arch package maintainer then?

yes, for you yes.

**Comment by andrew-ld** [comment]
https://bugs.archlinux.org/task/71745
