### ISSUE TITLE
segfault when no audio device was found

### ISSUE THREAD

**Issue by rindeal** [telegramdesktop/tdesktop#2281]
### Steps to reproduce
1. start telegram
2. immediate segfault

backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff5cc928d in ProbeDevices (list=list@entry=0x7ffff5f117a8 <alcCaptureDeviceList>, backendinfo=backendinfo@entry=0x7ffff5f117c0 <CaptureBackend>, type=type@entry=CAPTURE_DEVICE_PROBE)
    at /tmp/portage/media-libs/openal-1.17.2/work/openal-soft-1.17.2/Alc/ALc.c:1234
#2  0x00007ffff5ccb61a in ProbeCaptureDeviceList () at /tmp/portage/media-libs/openal-1.17.2/work/openal-soft-1.17.2/Alc/ALc.c:1246
#3  alcGetString (Device=0x0, param=<optimized out>) at /tmp/portage/media-libs/openal-1.17.2/work/openal-soft-1.17.2/Alc/ALc.c:2644
#4  0x0000000000503e3b in AudioCapture::check (this=this@entry=0x280e6e0) at ../../Telegram/SourceFiles/audio.cpp:782
#5  0x0000000000509e78 in audioInit () at ../../Telegram/SourceFiles/audio.cpp:106
#6  0x00000000004d9ec4 in App::initMedia () at ../../Telegram/SourceFiles/app.cpp:2082
#7  0x00000000004f59e4 in AppClass::AppClass (this=0x23862e0) at ../../Telegram/SourceFiles/application.cpp:729
#8  0x00000000004f6117 in Sandbox::launch () at ../../Telegram/SourceFiles/application.cpp:642
#9  0x00000000004f6206 in Application::singleInstanceChecked (this=this@entry=0x7fffffffe230) at ../../Telegram/SourceFiles/application.cpp:226
#10 0x00000000004f81a9 in Application::socketError (this=0x7fffffffe230, e=<optimized out>) at ../../Telegram/SourceFiles/application.cpp:198
#11 0x0000000000941525 in Application::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at GeneratedFiles/Release/moc_application.cpp:105
#12 0x000000000119daac in activate () at kernel/qobject.cpp:3730
#13 0x000000000119df69 in activate () at kernel/qobject.cpp:3595
#14 0x0000000000cd75f5 in error () at .moc/moc_qlocalsocket.cpp:221
#15 0x0000000000cdf6b4 in errorOccurred () at socket/qlocalsocket_unix.cpp:205
#16 0x0000000000cdfc2c in _q_connectToSocket () at socket/qlocalsocket_unix.cpp:287
#17 0x0000000000ce029e in connectToServer () at socket/qlocalsocket_unix.cpp:247
#18 0x0000000000cd7756 in connectToServer () at socket/qlocalsocket.cpp:380
#19 0x00000000004f7c5c in Application::Application (this=0x7fffffffe230, argc=<optimized out>, argv=<optimized out>) at ../../Telegram/SourceFiles/application.cpp:118
#20 0x000000000048d6e7 in main (argc=1, argv=0x7fffffffe388) at ../../Telegram/SourceFiles/main.cpp:61
```

### Configuration
**Operating system:** Gentoo
**Version of Telegram Desktop:** 0.9.56

**Comment by rindeal** [comment]
after recompiling OpenAL with alsa and pulseaudio support, everything worked fine again, so it's probably an OpenAL issue.
