### ISSUE TITLE
[Question] failed when compile breakpad on windows， need some help   -。-

### ISSUE THREAD

**Issue by xixi911** [telegramdesktop/tdesktop#25187]
Turn off this advice by setting config variable advice.detachedHead to false

Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
Exception in thread Thread-1 (_readerthread):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
Exception in thread Thread-1 (_readerthread):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
    self.run()
    self.run()
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
    buffer.append(fh.read())
    buffer.append(fh.read())
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
    buffer.append(fh.read())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
    buffer.append(fh.read())
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2468, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1972, in GenerateOutputForConfig
    gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes(
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 186, in ExtractSharedMSVSSystemIncludes
    env = GetGlobalVSMacroEnv(GetVSVersion(generator_flags))
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 168, in GetGlobalVSMacroEnv
    dxsdk_dir = _FindDirectXInstallation()
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 146, in _FindDirectXInstallation
    for line in p.communicate()[0].splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\SoftwareTools\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2494, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\SoftwareTools\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'splitlines'
[16\19](Libraries\breakpad): FAILED

**Comment by ilya-fedin** [comment]
#16939
