### ISSUE TITLE
failing pipe .... | docker buildx build -t tdesktop:centos_env -

### ISSUE THREAD

**Issue by gurucubano** [telegramdesktop/tdesktop#25381]
I run into the same problem as described in https://github.com/telegramdesktop/tdesktop/issues/24927 
I fetched the plugin and placed it into
```
/home/purism/.docker/cli-plugins/buildx-v0.9.1.linux-amd64"
/usr/lib/docker/cli-plugins/buildx-v0.9.1.linux-amd64
```
The docker version is very recent:
```
docker version
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.15
 Git commit:        55c4c88
 Built:             Mon May 30 18:34:49 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
```
And when I run the command to initialize the build, it fails with:
```
poetry run gen_dockerfile | docker buildx build -t tdesktop:centos_env -
unknown shorthand flag: 't' in -t
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
...
Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/purism/guru/tdesktop/Telegram/build/docker/centos_env/gen_dockerfile.py", line 4, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
```
Please advice how to fix this.

**Comment by ilya-fedin** [comment]
Install official Docker build from https://docs.docker.com/get-docker/, distributives provide a shrinked version
