### ISSUE TITLE
App crashes when trying to play video in picture-in-picture mode

### ISSUE THREAD

**Issue by SandaruKasa** [telegramdesktop/tdesktop#25433]
### Steps to reproduce

1. Open a video
2. Press the picture-in-picture button

### Expected behaviour

Video starts playing in a small floating box

### Actual behaviour

App freezes for a second and then crashes

### Operating system

Arch Linux, KDE Plasma 5.26.3 (xorg 21.1.4)

### Version of Telegram Desktop

4.3.3

### Installation source

Static binary from official website

### Logs

```
[2022.11.24 17:06:34] Launched version: 4003003, install beta: [TRUE], alpha: 0, debug mode: [FALSE]
[2022.11.24 17:06:34] Executable dir: /home/sandarukasa/.local/bin/telegram/, name: Telegram
[2022.11.24 17:06:34] Initial working dir: /home/sandarukasa/.local/share/TelegramDesktop/
[2022.11.24 17:06:34] Working dir: /home/sandarukasa/.local/share/TelegramDesktop/
[2022.11.24 17:06:34] Command line: /home/sandarukasa/.local/bin/telegram/Telegram -workdir /home/sandarukasa/.local/share/TelegramDesktop/ --
[2022.11.24 17:06:34] Executable path before check: /home/sandarukasa/.local/bin/telegram/Telegram
[2022.11.24 17:06:34] Logs started
[2022.11.24 17:06:34] Launcher filename: org.telegram.desktop.0b1eec69a876b85828a36cbecb48b2cb.desktop
[2022.11.24 17:06:34] Connecting local socket to /tmp/0b1eec69a876b85828a36cbecb48b2cb-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2022.11.24 17:06:34] This is the only instance of Telegram, starting server and app...
[2022.11.24 17:06:34] Moved logging from '/home/sandarukasa/.local/share/TelegramDesktop/log_start0.txt' to '/home/sandarukasa/.local/share/TelegramDesktop/log.txt'!
[2022.11.24 17:06:34] Primary screen DPI: 96
[2022.11.24 17:06:34] System tray available: [TRUE]
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 17:06:34] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2022.11.24 17:06:35] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2022.11.24 17:06:35] Icon theme: breeze-dark
[2022.11.24 17:06:35] Fallback icon theme: 
[2022.11.24 17:06:35] App Info: reading settings...
[2022.11.24 17:06:35] App Info: reading encrypted settings...
[2022.11.24 17:06:35] Lang Info: Loaded cached, keys: 4272
[2022.11.24 17:06:35] OpenAL Logging Level: (not set)
[2022.11.24 17:06:35] Audio Playback Devices: Family 17h/19h HD Audio Controller Analog Stereo
[2022.11.24 17:06:35] Audio Playback Default Device: Family 17h/19h HD Audio Controller Analog Stereo
[2022.11.24 17:06:35] Audio Capture Devices: Family 17h/19h HD Audio Controller Analog Stereo;Monitor of Family 17h/19h HD Audio Controller Analog Stereo
[2022.11.24 17:06:35] Audio Capture Default Device: Family 17h/19h HD Audio Controller Analog Stereo
[2022.11.24 17:06:35] Using Unity launcher counter.
[2022.11.24 17:06:35] App Info: reading accounts info...
[2022.11.24 17:06:35] App Info: reading encrypted info...
[2022.11.24 17:06:35] App Info: reading map...
[2022.11.24 17:06:35] App Info: reading encrypted map...
[2022.11.24 17:06:35] App Info: reading encrypted user settings...
[2022.11.24 17:06:35] App Info: encrypted user settings read.
[2022.11.24 17:06:35] App Info: reading encrypted mtp data...
[2022.11.24 17:06:35] MTP Info: read keys, current: 5, to destroy: 0
[2022.11.24 17:06:35] Map read time: 9
[2022.11.24 17:06:35] App Info: reading encrypted mtp config...
[2022.11.24 17:06:35] App Info: reading map...
[2022.11.24 17:06:35] App Info: reading encrypted map...
[2022.11.24 17:06:35] App Info: reading encrypted user settings...
[2022.11.24 17:06:35] App Info: encrypted user settings read.
[2022.11.24 17:06:35] App Info: reading encrypted mtp data...
[2022.11.24 17:06:35] MTP Info: read keys, current: 5, to destroy: 0
[2022.11.24 17:06:35] Map read time: 5
[2022.11.24 17:06:35] App Info: reading encrypted mtp config...
[2022.11.24 17:06:35] App Info: reading map...
[2022.11.24 17:06:35] App Info: reading encrypted map...
[2022.11.24 17:06:35] App Info: reading encrypted user settings...
[2022.11.24 17:06:35] App Info: encrypted user settings read.
[2022.11.24 17:06:35] App Info: reading encrypted mtp data...
[2022.11.24 17:06:35] MTP Info: read keys, current: 5, to destroy: 0
[2022.11.24 17:06:35] Map read time: 0
[2022.11.24 17:06:35] App Info: reading encrypted mtp config...
[2022.11.24 17:06:35] Export Info: Destroy top bar by controller removal.
[2022.11.24 17:06:35] OpenGL Profile: Compatibility.
[2022.11.24 17:06:35] OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.42, 5.15.79-1-lts)
[2022.11.24 17:06:35] OpenGL Vendor: AMD
[2022.11.24 17:06:35] OpenGL Version: 4.6 (Compatibility Profile) Mesa 22.2.3
[2022.11.24 17:06:35] OpenGL Extensions: GL_EXT_pixel_buffer_object, GL_ARB_conditional_render_inverted, GL_ARB_point_sprite, GL_NV_vdpau_interop, GL_ARB_shading_language_420pack, GL_ARB_gpu_shader_fp64, GL_ARB_query_buffer_object, GL_ARB_seamless_cubemap_per_texture, GL_ARB_shader_texture_lod, GL_SGIS_texture_edge_clamp, GL_ARB_texture_filter_anisotropic, GL_ARB_shader_objects, GL_ARB_compatibility, GL_ATI_meminfo, GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_stencil_export, GL_ARB_bindless_texture, GL_ARB_explicit_attrib_location, GL_ARB_sample_shading, GL_ARB_texture_storage_multisample, GL_EXT_secondary_color, GL_EXT_texture_filter_anisotropic, GL_AMD_shader_trinary_minmax, GL_ARB_texture_buffer_object, GL_ARB_pipeline_statistics_query, GL_EXT_memory_object_fd, GL_ARB_texture_query_levels, GL_EXT_texture_compression_s3tc, GL_ARB_texture_compression_rgtc, GL_EXT_texture_buffer_object, GL_ARB_spirv_extensions, GL_EXT_texture_shadow_lod, GL_EXT_packed_depth_stencil, GL_EXT_direct_state_access, GL_EXT_framebuffer_sRGB, GL_EXT_multi_draw_arrays, GL_EXT_point_parameters, GL_EXT_depth_bounds_test, GL_ARB_internalformat_query2, GL_ARB_separate_shader_objects, GL_EXT_framebuffer_object, GL_ARB_vertex_shader, GL_ARB_clear_buffer_object, GL_AMD_framebuffer_multisample_advanced, GL_EXT_semaphore_fd, GL_EXT_shadow_funcs, GL_NV_primitive_restart, GL_NV_blend_square, GL_NV_texture_barrier, GL_ARB_shader_ballot, GL_ARB_vertex_array_bgra, GL_KHR_robustness, GL_ARB_derivative_control, GL_ARB_sync, GL_EXT_vertex_array, GL_EXT_draw_buffers2, GL_ARB_ES3_2_compatibility, GL_ARB_internalformat_query, GL_ARB_transform_feedback2, GL_ARB_shader_draw_parameters, GL_INTEL_blackhole_render, GL_ANGLE_texture_compression_dxt5, GL_EXT_texture3D, GL_ARB_texture_border_clamp, GL_ARB_shader_atomic_counters, GL_EXT_vertex_array_bgra, GL_EXT_texture_cube_map, GL_IBM_multimode_draw_arrays, GL_ARB_shader_viewport_layer_array, GL_NV_texture_rectangle, GL_ARB_depth_texture, GL_S3_s3tc, GL_EXT_texture_integer, GL_KHR_robust_buffer_access_behavior, GL_MESA_framebuffer_flip_y, GL_ARB_shader_atomic_counter_ops, GL_EXT_texture_sRGB, GL_ARB_texture_float, GL_ARB_transform_feedback_instanced, GL_ARB_enhanced_layouts, GL_ARB_provoking_vertex, GL_ARB_cull_distance, GL_ARB_shader_group_vote, GL_ARB_texture_rectangle, GL_APPLE_packed_pixels, GL_KHR_texture_compression_astc_sliced_3d, GL_NV_shader_atomic_int64, GL_ARB_shader_precision, GL_ARB_texture_mirror_clamp_to_edge, GL_SGIS_generate_mipmap, GL_EXT_texture_compression_rgtc, GL_ARB_ES3_compatibility, GL_ARB_transform_feedback_overflow_query, GL_ARB_shader_bit_encoding, GL_EXT_texture_shared_exponent, GL_ARB_parallel_shader_compile, GL_EXT_packed_float, GL_ARB_texture_cube_map_array, GL_AMD_query_buffer_object, GL_KHR_parallel_shader_compile, GL_MESA_pack_invert, GL_SGIS_texture_border_clamp, GL_EXT_shader_image_load_store, GL_ARB_copy_image, GL_ARB_gpu_shader5, GL_AMD_performance_monitor, GL_NVX_gpu_memory_info, GL_KHR_no_error, GL_EXT_shader_integer_mix, GL_NV_light_max_exponent, GL_NV_texgen_reflection, GL_ARB_texture_env_crossbar, GL_ARB_framebuffer_object, GL_EXT_bgra, GL_ARB_texture_multisample, GL_EXT_blend_func_separate, GL_EXT_texture, GL_ARB_sparse_texture_clamp, GL_ARB_buffer_storage, GL_ARB_timer_query, GL_ARB_framebuffer_sRGB, GL_EXT_transform_feedback, GL_ARB_vertex_buffer_object, GL_AMD_conservative_depth, GL_ARB_sampler_objects, GL_ARB_shading_language_packing, GL_ARB_gpu_shader_int64, GL_IBM_rasterpos_clip, GL_EXT_semaphore, GL_MESA_texture_signed_rgba, GL_EXT_fog_coord, GL_ARB_multi_bind, GL_ARB_texture_cube_map, GL_ARB_ES3_1_compatibility, GL_ARB_arrays_of_arrays, GL_ARB_direct_state_access, GL_ARB_occlusion_query, GL_EXT_texture_snorm, GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_draw_instanced, GL_EXT_rescale_normal, GL_EXT_texture_swizzle, GL_NV_depth_clamp, GL_ARB_pixel_buffer_object, GL_ARB_fragment_shader, GL_EXT_gpu_shader4, GL_EXT_packed_pixels, GL_ARB_texture_view, GL_KHR_texture_compression_astc_ldr, GL_ARB_seamless_cube_map, GL_ARB_compute_variable_group_size, GL_ARB_multitexture, GL_ARB_gl_spirv, GL_ARB_texture_buffer_range, GL_ARB_vertex_attrib_64bit, GL_ATI_texture_env_combine3, GL_EXT_vertex_attrib_64bit, GL_ATI_fragment_shader, GL_OES_EGL_image, GL_ARB_conservative_depth, GL_ATI_texture_float, GL_EXT_texture_array, GL_ARB_vertex_program, GL_ARB_shader_texture_image_samples, GL_EXT_window_rectangles, GL_NV_copy_depth_to_color, GL_ARB_clear_texture, GL_ARB_shader_stencil_export, GL_ARB_multi_draw_indirect, GL_AMD_draw_buffers_blend, GL_ARB_base_instance, GL_ARB_texture_non_power_of_two, GL_ARB_fragment_layer_viewport, GL_ARB_robust_buffer_access_behavior, GL_ARB_tessellation_shader, GL_EXT_blend_minmax, GL_ARB_get_program_binary, GL_EXT_draw_instanced, GL_MESA_shader_integer_functions, GL_EXT_memory_object, GL_EXT_texture_object, GL_AMD_pinned_memory, GL_ARB_texture_barrier, GL_EXT_blend_equation_separate, GL_ANGLE_texture_compression_dxt3, GL_ARB_shader_subroutine, GL_AMD_multi_draw_indirect, GL_EXT_texture_compression_dxt1, GL_EXT_timer_query, GL_ARB_color_buffer_float, GL_EXT_texture_sRGB_R8, GL_EXT_compiled_vertex_array, GL_EXT_polygon_offset_clamp, GL_EXT_framebuffer_multisample, GL_ARB_viewport_array, GL_ARB_compute_shader, GL_ARB_instanced_arrays, GL_ARB_vertex_type_2_10_10_10_rev, GL_ARB_texture_swizzle, GL_ARB_shading_language_include, GL_ARB_texture_storage, GL_ARB_transform_feedback3, GL_NV_conditional_render, GL_ARB_indirect_parameters, GL_NV_copy_image, GL_EXT_EGL_image_storage, GL_EXT_draw_range_elements, GL_ARB_texture_env_add, GL_ARB_compressed_texture_pixel_storage, GL_ARB_point_parameters, GL_EXT_stencil_two_side, GL_ARB_vertex_attrib_binding, GL_AMD_vertex_shader_viewport_index, GL_ARB_half_float_vertex, GL_ARB_framebuffer_no_attachments, GL_AMD_depth_clamp_separate, GL_ARB_texture_mirrored_repeat, GL_ARB_texture_query_lod, GL_KHR_debug, GL_ARB_texture_stencil8, GL_EXT_texture_env_add, GL_ARB_depth_clamp, GL_ARB_half_float_pixel, GL_SGIS_texture_lod, GL_EXT_blend_color, GL_ARB_ES2_compatibility, GL_EXT_abgr, GL_EXT_copy_texture, GL_ARB_window_pos, GL_OES_read_format, GL_EXT_EGL_sync, GL_EXT_separate_specular_color, GL_ARB_clip_control, GL_ARB_program_interface_query, GL_KHR_blend_equation_advanced, GL_ATI_texture_mirror_once, GL_ARB_vertex_array_object, GL_ARB_draw_buffers_blend, GL_EXT_stencil_wrap, GL_ARB_blend_func_extended, GL_ARB_shader_image_size, GL_SUN_multi_draw_arrays, GL_ARB_texture_compression, GL_ARB_occlusion_query2, GL_NV_packed_depth_stencil, GL_ARB_fragment_coord_conventions, GL_ARB_shadow, GL_EXT_texture_compression_latc, GL_ARB_draw_elements_base_vertex, GL_EXT_framebuffer_blit, GL_ARB_texture_gather, GL_EXT_blend_subtract, GL_AMD_texture_texture4, GL_ARB_sparse_texture, GL_ARB_draw_indirect, GL_ARB_texture_compression_bptc, GL_ARB_stencil_texturing, GL_ARB_get_texture_sub_image, GL_INGR_blend_func_separate, GL_EXT_texture_edge_clamp, GL_ARB_explicit_uniform_location, GL_ATI_texture_compression_3dc, GL_EXT_provoking_vertex, GL_EXT_texture_rectangle, GL_ARB_polygon_offset_clamp, GL_ARB_sparse_texture2, GL_IBM_texture_mirrored_repeat, GL_ARB_fragment_program, GL_EXT_texture_mirror_clamp, GL_ARB_texture_rgb10_a2ui, GL_ARB_invalidate_subdata, GL_EXT_texture_sRGB_decode, GL_EXT_texture_env_combine, GL_NV_fog_distance, GL_EXT_subtexture, GL_MESA_window_pos, GL_ARB_map_buffer_range, GL_ARB_sparse_buffer, GL_NV_compute_shader_derivatives, GL_ARB_copy_buffer, GL_ARB_depth_buffer_float, GL_EXT_gpu_program_parameters, GL_KHR_context_flush_control, GL_EXT_shader_image_load_formatted, GL_ARB_multisample, GL_ARB_robustness, GL_ARB_shading_language_100, GL_ARB_transpose_matrix, GL_ARB_texture_buffer_object_rgb32, GL_ARB_texture_env_dot3, GL_ATI_blend_equation_separate, GL_ATI_draw_buffers, GL_EXT_shader_samples_identical, GL_ARB_texture_env_combine, GL_ARB_shader_clock, GL_ARB_shader_storage_buffer_object, GL_ARB_draw_buffers, GL_ARB_shader_image_load_store, GL_EXT_texture_lod_bias, GL_NV_half_float, GL_ARB_fragment_program_shadow, GL_ARB_uniform_buffer_object, GL_ATI_separate_stencil, GL_ARB_debug_output, GL_NV_texture_env_combine4, GL_AMD_vertex_shader_layer, GL_ARB_texture_rg, GL_ARB_map_buffer_alignment, GL_EXT_demote_to_helper_invocation, GL_EXT_framebuffer_multisample_blit_scaled, GL_NV_alpha_to_coverage_dither_control, GL_EXT_texture_env_dot3
[2022.11.24 17:06:35] OpenGL: QOpenGLContext created, version: 4.4.
[2022.11.24 17:06:35] OpenGL: [TRUE] (OverlayWidget)
[2022.11.24 17:06:35] Notification daemon product name: Plasma
[2022.11.24 17:06:35] Notification daemon vendor name: KDE
[2022.11.24 17:06:35] Notification daemon version: 5.26.3
[2022.11.24 17:06:35] Notification daemon specification version: 1.2
[2022.11.24 17:06:35] Notification daemon capabilities: body, body-hyperlinks, body-markup, body-images, icon-static, actions, persistence, inline-reply, x-kde-urls, x-kde-origin-name, x-kde-display-appname, inhibitions
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:36] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:37] RPC Error: request 150 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2022.11.24 17:06:37] RPC Error: request 151 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2022.11.24 17:06:39] RPC Error: request 316 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2022.11.24 17:06:39] RPC Error: request 347 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2022.11.24 17:06:39] RPC Error: request 373 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2022.11.24 17:06:39] API Warning: not loaded minimal channel applied.
[2022.11.24 17:06:41] Audio Info: recreating audio device and reattaching the tracks
[2022.11.24 17:06:41] Streaming Error: Error in av_hwdevice_ctx_create (code: -1313558101, text: Unknown error occurred).
[2022.11.24 17:06:43] OpenGL: [TRUE] (PipPanel)
```

**Comment by TadavomnisT** [comment]
Same thing goes on Debian binary after new update.
zsh log:
```
zsh: segmentation fault  Documents/Telegram
```

gdb stack trace of the Segmentation Fault:
```
Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x00007ffff7760609 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7760609 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffd038caf0 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#2  0x00007fffd032de0f in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007fffcff43235 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x0000000002d00b17 in ?? ()
#5  0x0000000002484522 in ?? ()
#6  0x00000000024a45c3 in ?? ()
#7  0x00000000024a4bf9 in ?? ()
#8  0x0000000002c9bd52 in ?? ()
#9  0x0000000004c892c7 in ?? ()
#10 0x0000000004a6bd4b in ?? ()
#11 0x0000000002d46fc6 in ?? ()
#12 0x0000000004be177d in ?? ()
#13 0x0000000004be4f1e in ?? ()
#14 0x0000000001a19c6e in ?? ()
#15 0x0000000005386d70 in ?? ()
#16 0x0000000004bde9f3 in ?? ()
#17 0x0000000004c358bf in ?? ()
#18 0x0000000004c3d778 in ?? ()
#19 0x0000000004c896be in ?? ()
#20 0x0000000004a6bd4b in ?? ()
#21 0x0000000002d46fc6 in ?? ()
#22 0x0000000004be177d in ?? ()
#23 0x0000000004be4f1e in ?? ()
#24 0x0000000001a19c6e in ?? ()
#25 0x0000000005386d70 in ?? ()
#26 0x00000000053872c7 in ?? ()
#27 0x000000000552594a in ?? ()
#28 0x00007ffff794e739 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff794e9c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff794ea5c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00000000054bf48f in ?? ()
#32 0x0000000004245ec4 in ?? ()
#33 0x0000000005387906 in ?? ()
#34 0x0000000001a5111e in ?? ()
#35 0x0000000001a53185 in ?? ()
#36 0x0000000001a554a6 in ?? ()
#37 0x000000000263f89a in ?? ()
#38 0x0000000000b5c542 in main ()

```

**Comment by rdschmidt** [comment]
Same on Linux Mint 21 (Telegram 4.3.3)

**Comment by Aokromes** [comment]
duplicate.
