### ISSUE TITLE
windows x64 build breakpad error

### ISSUE THREAD

**Issue by gytai** [telegramdesktop/tdesktop#25583]
### Steps to reproduce

1. git clone code
2. tdesktop\Telegram\build\prepare\win.bat

### Expected behaviour

prepare env is ok

### Actual behaviour

Describe the solution you'd like
Turn off this advice by setting config variable advice.detachedHead to false

Exception in thread Thread-1 (_handle_workers):
Traceback (most recent call last):
File "C:\TBuild\ThirdParty\Python39\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\TBuild\ThirdParty\Python39\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "C:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 522, in _handle_workers
cls._wait_for_updates(current_sentinels, change_notifier)
File "C:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 502, in _wait_for_updates
wait(sentinels, timeout=timeout)
File "C:\TBuild\ThirdParty\Python39\lib\multiprocessing\connection.py", line 879, in wait
ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
File "C:\TBuild\ThirdParty\Python39\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 194

### Operating system

window server 2019

### Version of Telegram Desktop

v4.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The instruction says to use Python 3.10, but you're using Python 3.9

**Comment by john-preston** [comment]
Is it working on the latest dev?
