### ISSUE TITLE
build on windows 10 64 system error

### ISSUE THREAD

**Issue by xiedeacc** [telegramdesktop/tdesktop#25612]
### Steps to reproduce

error execute tdesktop\Telegram\build\prepare\win.bat, I guess my os is a chinese system problem?

```
D:\code\ThirdParty\gyp\pylib\gyp\input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
Exception in thread Thread-1 (_readerthread):
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1 (_readerthread):
Exception in thread Thread-1 (_readerthread):
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self.run()
    self.run()
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
  File "C:\Program Files\Python310\lib\subprocess.py", line 1497, in _readerthread
    buffer.append(fh.read())
    buffer.append(fh.read())
    buffer.append(fh.read())
    buffer.append(fh.read())
    buffer.append(fh.read())
    buffer.append(fh.read())
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
  File "C:\Program Files\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 56: invalid continuation byte
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\code\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2468, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "D:\code\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1972, in GenerateOutputForConfig
    gyp.msvs_emulation.ExtractSharedMSVSSystemIncludes(
  File "D:\code\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 186, in ExtractSharedMSVSSystemIncludes
    env = GetGlobalVSMacroEnv(GetVSVersion(generator_flags))
  File "D:\code\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 168, in GetGlobalVSMacroEnv
    dxsdk_dir = _FindDirectXInstallation()
  File "D:\code\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 146, in _FindDirectXInstallation
    for line in p.communicate()[0].splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\code\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "D:\code\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "D:\code\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\code\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2494, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'splitlines'
[22/26](Libraries/breakpad): FAILED
FAILED

D:\code\tbuild>

```

### Expected behaviour

execute tdesktop\Telegram\build\prepare\win.bat successfully

### Actual behaviour

execute tdesktop\Telegram\build\prepare\win.bat failed

### Operating system

windows 10 64bit, chinese version

### Version of Telegram Desktop

95b29f5f353c16e090f0e1ae7f43155ef9a0af69

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16939
