### ISSUE TITLE
error MSB6001: Invalid command line switch for "CL.exe"

### ISSUE THREAD

**Issue by xiedeacc** [telegramdesktop/tdesktop#25619]
### Steps to reproduce

I followd https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md, generated Telegram.sln successfully, 
my os is win10 64, vs 2022 enterprize
but build Telegram failed, somtimes will say lib not found, sometimes said styles/palette.h not found

```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
2>------ Build started: Project: win_directx_helper, Configuration: Debug x64 ------
3>------ Build started: Project: td_scheme_scheme, Configuration: Debug x64 ------
4>------ Build started: Project: lib_tgvoip_bundled, Configuration: Debug x64 ------
5>------ Build started: Project: lib_tgcalls, Configuration: Debug x64 ------
6>------ Build started: Project: external_rlottie_bundled, Configuration: Debug x64 ------
7>------ Build started: Project: external_qr_code_generator_bundled, Configuration: Debug x64 ------
8>------ Build started: Project: external_minizip_bundled, Configuration: Debug x64 ------
9>------ Build started: Project: external_lz4_bundled, Configuration: Debug x64 ------
10>------ Build started: Project: external_hunspell_bundled, Configuration: Debug x64 ------
11>------ Build started: Project: external_cld3_bundled_task_spec.proto, Configuration: Debug x64 ------
12>------ Build started: Project: external_cld3_bundled_sentence.proto, Configuration: Debug x64 ------
13>------ Build started: Project: external_cld3_bundled_feature_extractor.proto, Configuration: Debug x64 ------
14>------ Build started: Project: Telegram_midl, Configuration: Debug x64 ------
2>win_directx_helper.cpp
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001: Invalid command line switch for "CL.exe". System.ArgumentException: Item has already been added. Key in dictionary: 'TMP'  Key being added: 'tmp'
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool, String commandLineCommands, String responseFileSwitch)
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.TrackerExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
4>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.Execute()
4>Done building project "lib_tgvoip_bundled.vcxproj" -- FAILED.
6>external_rlottie_bundled.vcxproj -> D:\code\tbuild\tdesktop\out\cmake\external\rlottie\Debug\external_rlottie_bundled.lib
7>external_qr_code_generator_bundled.vcxproj -> D:\code\tbuild\tdesktop\out\cmake\external\qr_code_generator\Debug\external_qr_code_generator_bundled.lib
9>external_lz4_bundled.vcxproj -> D:\code\tbuild\tdesktop\out\cmake\external\lz4\Debug\external_lz4_bundled.lib
8>external_minizip_bundled.vcxproj -> D:\code\tbuild\tdesktop\out\cmake\external\minizip\Debug\external_minizip_bundled.lib
5>lib_tgcalls.vcxproj -> D:\code\tbuild\tdesktop\out\Telegram\Debug\lib_tgcalls.lib
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001: Invalid command line switch for "CL.exe". System.ArgumentException: Item has already been added. Key in dictionary: 'TMP'  Key being added: 'tmp'
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool, String commandLineCommands, String responseFileSwitch)
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.TrackerExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
10>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    at Microsoft.Build.Utilities.ToolTask.Execute()
10>Done building project "external_hunspell_bundled.vcxproj" -- FAILED.
15>------ Build started: Project: external_cld3_bundled, Configuration: Debug x64 ------
16>------ Build started: Project: lib_tgcalls_legacy, Configuration: Debug x64 ------
16>lib_tgcalls_legacy.vcxproj -> D:\code\tbuild\tdesktop\out\Telegram\Debug\lib_tgcalls_legacy.lib
15>feature_extractor.pb.cc
```

![image](https://user-images.githubusercontent.com/8072296/209652209-08d4ec3b-b4f8-416a-89e3-950ba46f8f8d.png)
![image](https://user-images.githubusercontent.com/8072296/209652241-41cfb74e-3ed3-4cd2-a0b5-bd7bfcdd1e82.png)

### Expected behaviour

build succefully

### Actual behaviour

build failed

### Operating system

win10 64bit, english version

### Version of Telegram Desktop

95b29f5f353c16e090f0e1ae7f43155ef9a0af69

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
`cmake --version`

**Comment by xiedeacc** [comment]
after update system, and reboot, everything goes well
