### ISSUE TITLE
SEGV in MTP::Instance::Private::unregisterRequest

### ISSUE THREAD

**Issue by blackgnezdo** [telegramdesktop/tdesktop#26446]
### Steps to reproduce

I was closing the app and it crashed with a core dump instead of exiting cleanly.

### Expected behaviour

Clean exit, not core dump.

### Actual behaviour

Crash, core dump

### Operating system

OpenBSD-7.3, bare xmonad

### Version of Telegram Desktop

tdesktop-4.8.4 from OpenBSD official package

### Installation source

Other (unofficial) source

### Logs

```shell
The stack trace from the core file:


#0  std::__1::__tree<std::__1::__value_type<int, int>, std::__1::__map_value_compare<int, std::__1::__value_type<int, int>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, int> > >::__root (this=<optimized out>) at /usr/include/c++/v1/__tree:1081
#1  std::__1::__tree<std::__1::__value_type<int, int>, std::__1::__map_value_compare<int, std::__1::__value_type<int, int>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, int> > >::find<int> (this=<optimized out>, __v=<optimized out>) at /usr/include/c++/v1/__tree:2468
#2  std::__1::__tree<std::__1::__value_type<int, int>, std::__1::__map_value_compare<int, std::__1::__value_type<int, int>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, int> > >::__erase_unique<int> (this=<optimized out>, __k=<optimized out>) at /usr/include/c++/v1/__tree:2444
#3  std::__1::map<int, int, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, int> > >::erase (this=<optimized out>, __k=<optimized out>)
    at /usr/include/c++/v1/map:1331
#4  MTP::Instance::Private::unregisterRequest (this=0x18d97c6b000, requestId=1022)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/mtproto/mtp_instance.cpp:1033
#5  0x0000018b75f4eec9 in MTP::Instance::Private::processCallback (this=0x18d97c6b000, response=...)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/mtproto/mtp_instance.cpp:1164
#6  0x0000018b75f6bfb6 in MTP::details::Session::tryToReceive (this=<optimized out>)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/mtproto/session.cpp:565
#7  0x0000018b748ad3a8 in std::__1::__function::__value_func<void ()>::operator()() const (this=<optimized out>)
    at /usr/include/c++/v1/__functional/function.h:498
#8  std::__1::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/v1/__functional/function.h:1175
#9  base::unique_function<void ()>::operator()() (this=<optimized out>)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/lib_base/base/unique_function.h:127
#10 base::InvokeQueuedEvent::invoke (this=0x18d7e392540) at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/lib_base/base/invoke_queued.h:26
#11 Core::Sandbox::notifyOrInvoke (this=0x75d3b07af9a0, receiver=0x18df42f0000, e=0x18d7e392540)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/core/sandbox.cpp:584
#12 Core::Sandbox::notify (this=0x75d3b07af9a0, receiver=0x18df42f0000, e=0x18d7e392540)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/core/sandbox.cpp:603
#13 0x0000018e20d69a7c in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/libQt6Core.so.2.0
#14 0x0000018e20d6aba2 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/local/lib/libQt6Core.so.2.0
#15 0x0000018e2100d829 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /usr/local/lib/libQt6Core.so.2.0
#16 0x0000018df3aa63ef in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.4201.10
#17 0x0000018df3aa6757 in g_main_context_iterate () from /usr/local/lib/libglib-2.0.so.4201.10
#18 0x0000018df3aa680b in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.4201.10
#19 0x0000018e2100d0e2 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt6Core.so.2.0
#20 0x0000018e20d7376c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt6Core.so.2.0
#21 0x0000018b7612bd49 in Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8::operator()() const (this=0x18e5ea58fa0)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/platform/linux/integration_linux.cpp:234
#22 std::__1::__invoke<Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8&>(Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8&) (__f=...) at /usr/include/c++/v1/type_traits:3918
#23 std::__1::invoke<Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8&>(Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8&) (__f=...) at /usr/include/c++/v1/__functional/invoke.h:93
#24 sigc::adaptor_functor<Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8>::operator()<>() const (this=0x18e5ea58fa0)
    at /usr/local/include/sigc++-3.0/sigc++/adaptors/adaptor_trait.h:100
#25 sigc::internal::slot_call<Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication()::$_8, void>::call_it(sigc::internal::slot_rep*) (
    rep=<optimized out>) at /usr/local/include/sigc++-3.0/sigc++/functors/slot.h:154
#26 0x0000018de0fea4a7 in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () from /usr/local/lib/libglibmm-2.68.so.0.2
#27 0x0000018df2a8abc5 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.4200.17
#28 0x0000018df2aa57a7 in signal_emit_unlocked_R () from /usr/local/lib/libgobject-2.0.so.4200.17
#29 0x0000018df2aa6642 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.4200.17
#30 0x0000018df2aa6a15 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.4200.17
#31 0x0000018df8b2d2cd in g_application_register () from /usr/local/lib/libgio-2.0.so.4200.17
#32 0x0000018df8b2da2b in g_application_run () from /usr/local/lib/libgio-2.0.so.4200.17
#33 0x0000018b7612b621 in Platform::(anonymous namespace)::LinuxIntegration::LaunchNativeApplication ()
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/platform/linux/integration_linux.cpp:313
#34 Platform::(anonymous namespace)::LinuxIntegration::init()::$_6::operator()() const (this=<optimized out>)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/platform/linux/integration_linux.cpp:151
#35 std::__1::__invoke<Platform::(anonymous namespace)::LinuxIntegration::init()::$_6&>(Platform::(anonymous namespace)::LinuxIntegration::init()::$_6&) (
    __f=...) at /usr/include/c++/v1/type_traits:3918
#36 std::__1::invoke<Platform::(anonymous namespace)::LinuxIntegration::init()::$_6&>(Platform::(anonymous namespace)::LinuxIntegration::init()::$_6&) (
    __f=...) at /usr/include/c++/v1/__functional/invoke.h:93
#37 sigc::adaptor_functor<Platform::(anonymous namespace)::LinuxIntegration::init()::$_6>::operator()<>() const (this=<optimized out>)
    at /usr/local/include/sigc++-3.0/sigc++/adaptors/adaptor_trait.h:100
#38 sigc::internal::slot_call<Platform::(anonymous namespace)::LinuxIntegration::init()::$_6, void>::call_it(sigc::internal::slot_rep*) (rep=<optimized out>)
    at /usr/local/include/sigc++-3.0/sigc++/functors/slot.h:154
#39 0x0000018de0fe5895 in (anonymous namespace)::glibmm_source_callback_once(void*) () from /usr/local/lib/libglibmm-2.68.so.0.2
#40 0x0000018df3aa63ef in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.4201.10
#41 0x0000018df3aa6757 in g_main_context_iterate () from /usr/local/lib/libglib-2.0.so.4201.10
#42 0x0000018df3aa680b in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.4201.10
#43 0x0000018e2100d0e2 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt6Core.so.2.0
#44 0x0000018e20d7376c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/libQt6Core.so.2.0
#45 0x0000018e20d6a266 in QCoreApplication::exec() () from /usr/local/lib/libQt6Core.so.2.0
#46 0x0000018b748a7432 in Core::Sandbox::start (this=0x75d3b07af9a0)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/core/sandbox.cpp:180
#47 0x0000018b7488c329 in Core::Launcher::executeApplication (this=<optimized out>)
    at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/core/launcher.cpp:569
#48 0x0000018b7488bbc0 in Core::Launcher::exec (this=0x18d99f47cb0) at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/core/launcher.cpp:376
#49 0x0000018b76125c4a in Platform::Launcher::exec (this=0x18d99f47cb0) at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/platform/linux/launcher_linux.cpp:60
#50 0x0000018b76b6c41d in main (argc=<optimized out>, argv=<optimized out>) at /usr/obj/ports/tdesktop-4.8.4/tdesktop-4.8.4-full/Telegram/SourceFiles/main.cpp:12

```
```

**Comment by blackgnezdo** [comment]
Crashed instruction:
```
=> 0x0000018b75f4ad80 <+272>:	mov    0x2e8(%r14),%rdi
...
(gdb) p/x $r14
$2 = 0x18d97c6b000
```

**Comment by ilya-fedin** [comment]
This looks like a bug in your standard C++ library
