### ISSUE TITLE
how Prepare Google Breakpad

### ISSUE THREAD

**Issue by jamesmoriati** [telegramdesktop/tdesktop#2743]
Please give a sure solution.
Whatever it was, but I did not.

my run and error
C:\Program Files (x86)\VC>e:
E:\>cd E:\TBuild\Libraries\depot_tools
E:\TBuild\Libraries\depot_tools>gclient config "https://chromium.googlesource.co
m/breakpad/breakpad.git"

Bootstrapping cipd client for windows-386...
From https://chrome-infra-packages.appspot.com/client?platform=windows-386&vers
ion=git_revision:05844bd9d1200cba8449b936b76e25eb90eabe25
[P6844 14:48:38.820 client.go:1209 I] Packages to be installed:
[P6844 14:48:38.820 client.go:1211 I]   infra/depot_tools/git_installer/windows-
amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P6844 14:48:38.827 client.go:1068 I] cipd: resolving fetch URL for infra/depot_
tools/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P6844 14:48:39.209 storage.go:249 I] cipd: initiating the fetch
[P6844 14:48:39.948 storage.go:214 I] cipd: about to fetch 29.4 Mb
[P6844 14:48:39.949 storage.go:205 I] cipd: fetching - 0%
[P6844 14:48:44.949 storage.go:205 I] cipd: fetching - 22%
[P6844 14:48:49.958 storage.go:205 I] cipd: fetching - 41%
[P6844 14:48:54.968 storage.go:205 I] cipd: fetching - 59%
[P6844 14:48:59.979 storage.go:205 I] cipd: fetching - 77%
[P6844 14:49:04.992 storage.go:205 I] cipd: fetching - 90%
[P6844 14:49:08.220 storage.go:205 I] cipd: fetching - 100%
[P6844 14:49:08.220 storage.go:205 I] cipd: fetching - 100%
[P6844 14:49:08.220 storage.go:221 I] cipd: fetch finished successfully
[P6844 14:49:08.221 client.go:1023 I] cipd: successfully fetched infra/depot_too
ls/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P6844 14:49:08.311 deployer.go:138 I] Deploying infra/depot_tools/git_installer
/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362 into c:\users\james\appd
ata\local\temp\tmpotne56
[P6844 14:49:08.312 reader.go:162 I] cipd: about to extract 29.4 Mb
[P6844 14:49:08.389 reader.go:172 I] cipd: extracting - 99%
[P6844 14:49:08.391 reader.go:172 I] cipd: extracting - 100%
[P6844 14:49:08.897 deployer.go:228 I] Successfully deployed infra/depot_tools/g
it_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P6844 14:49:08.901 client.go:1274 I] All changes applied.
Traceback (most recent call last):
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 193, in <module>
    sys.exit(main(sys.argv[1:]))
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 185, in main
    install_git(args, git_version, git_directory)
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 115, in install_git
    '-Directory="%s"' % git_directory.replace('\\', '\\\\'),
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 26, in _check_call
    subprocess.check_call(argv, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jamesmoriati** [comment]
please, help me.

**Comment by jamesmoriati** [comment]
first run and error : The system cannot find the path specified.

C:\Program Files (x86)\VC>E:

E:\>cd E:\TBuild\Libraries

E:\TBuild\Libraries>git clone https://chromium.googlesource.com/chromium/tools/d
epot_tools.git

Cloning into 'depot_tools'...
remote: Sending approximately 21.83 MiB ...
remote: Total 18768 (delta 12223), reused 18768 (delta 12223)R
Receiving objects: 100% (18768/18768), 21.83 MiB | 529.00 KiB/s, done.
Resolving deltas: 100% (12223/12223), done.

E:\TBuild\Libraries>cd depot_tools

E:\TBuild\Libraries\depot_tools>SET PATH=%PATH%;C:\Python27;

E:\TBuild\Libraries\depot_tools>path

PATH=C:\Program Files (x86)\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:
\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\;C:\Program Files (x86
)\MSBuild\14.0\bin;C:\Program Files (x86)\Common7\IDE\;C:\Program Files (x86)\VC
\BIN;C:\Program Files (x86)\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.
0.30319;C:\Program Files (x86)\VC\VCPackages;C:\Program Files (x86)\HTML Help Wo
rkshop;C:\Program Files (x86)\Team Tools\Performance Tools;C:\Program Files (x86
)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\b
in\NETFX 4.6.1 Tools\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)
\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Pr
ogram Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System3
2\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(
R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Manage
ment Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Com
ponents\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\I
PT;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Micros
oft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Bin
n\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Prog
ram Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Micr
osoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microso
ft SQL Server\120\DTS\Binn\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:
\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Window
s Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files\MATLAB\R2
016a\runtime\win64;C:\Program Files\MATLAB\R2016a\bin;C:\Program Files\MATLAB\R2
016a\polyspace\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Prog
ram Files\Git\cmd;D:\TBuild\Libraries\ninja;C:\Program Files\010 Editor;D:\TBuil
d\Libraries\qt5_6_2\qtbase\bin;C:\Program Files\strawberry-perl-5.22.1.3-64bit-P
DL\perl\bin;C:\Python27;

(where C:\Python27 is path install python-2.7.12)

E:\TBuild\Libraries\depot_tools>gclient config "https://chromium.googlesource.co
m/breakpad/breakpad.git"
Installing python 2.7.6...
Fetching from https://storage.googleapis.com/chrome-infra/python276_bin.zip
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by jamesmoriati** [comment]
second run and error : 
first Extract python276_bin.zip to E:\TBuild\Libraries\depot_tools and run follow comands:

C:\Program Files (x86)\VC>E:

E:\>cd E:\TBuild\Libraries

E:\TBuild\Libraries>git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 21.83 MiB ...
remote: Total 18768 (delta 12223), reused 18768 (delta 12223) eceiving objects:
Receiving objects: 100% (18768/18768), 21.62 MiB
Receiving objects: 100% (18768/18768), 21.83 MiB | 476.00 KiB/s, done.
Resolving deltas: 100% (12223/12223), done.

E:\TBuild\Libraries>cd depot_tools

E:\TBuild\Libraries\depot_tools>SET PATH=%PATH%;C:\Python27;

E:\TBuild\Libraries\depot_tools>path
PATH=C:\Program Files (x86)\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:
\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\;C:\Program Files (x86
)\MSBuild\14.0\bin;C:\Program Files (x86)\Common7\IDE\;C:\Program Files (x86)\VC
\BIN;C:\Program Files (x86)\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.
0.30319;C:\Program Files (x86)\VC\VCPackages;C:\Program Files (x86)\HTML Help Wo
rkshop;C:\Program Files (x86)\Team Tools\Performance Tools;C:\Program Files (x86
)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\b
in\NETFX 4.6.1 Tools\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)
\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Pr
ogram Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System3
2\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(
R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Manage
ment Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Com
ponents\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\I
PT;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Micros
oft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Bin
n\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Prog
ram Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Micr
osoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microso
ft SQL Server\120\DTS\Binn\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:
\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Window
s Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files\MATLAB\R2
016a\runtime\win64;C:\Program Files\MATLAB\R2016a\bin;C:\Program Files\MATLAB\R2
016a\polyspace\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Prog
ram Files\Git\cmd;D:\TBuild\Libraries\ninja;C:\Program Files\010 Editor;D:\TBuil
d\Libraries\qt5_6_2\qtbase\bin;C:\Program Files\strawberry-perl-5.22.1.3-64bit-P
DL\perl\bin;C:\Python27;

(C:\Python27 is path install python-2.7.12)

E:\TBuild\Libraries\depot_tools>gclient config "https://chromium.googlesource.com/breakpad/breakpad.git"

Installing python 2.7.6...
Fetching from https://storage.googleapis.com/chrome-infra/python276_bin.zip
Bootstrapping cipd client for windows-386...
From https://chrome-infra-packages.appspot.com/client?platform=windows-386&vers
ion=git_revision:05844bd9d1200cba8449b936b76e25eb90eabe25
[P9764 17:06:51.706 client.go:1209 I] Packages to be installed:
[P9764 17:06:51.706 client.go:1211 I]   infra/depot_tools/git_installer/windows-
amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9764 17:06:51.721 client.go:1068 I] cipd: resolving fetch URL for infra/depot_
tools/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9764 17:06:52.078 storage.go:249 I] cipd: initiating the fetch
[P9764 17:06:52.796 storage.go:214 I] cipd: about to fetch 29.4 Mb
[P9764 17:06:52.797 storage.go:205 I] cipd: fetching - 0%
[P9764 17:06:57.816 storage.go:205 I] cipd: fetching - 12%
[P9764 17:07:02.835 storage.go:205 I] cipd: fetching - 33%
[P9764 17:07:07.990 storage.go:205 I] cipd: fetching - 53%
[P9764 17:07:12.991 storage.go:205 I] cipd: fetching - 77%
[P9764 17:07:17.631 storage.go:205 I] cipd: fetching - 100%
[P9764 17:07:17.631 storage.go:205 I] cipd: fetching - 100%
[P9764 17:07:17.631 storage.go:221 I] cipd: fetch finished successfully
[P9764 17:07:17.631 client.go:1023 I] cipd: successfully fetched infra/depot_too
ls/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9764 17:07:17.704 deployer.go:138 I] Deploying infra/depot_tools/git_installer
/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362 into c:\users\james\appd
ata\local\temp\tmpnd2198
[P9764 17:07:17.706 reader.go:162 I] cipd: about to extract 29.4 Mb
[P9764 17:07:17.786 reader.go:172 I] cipd: extracting - 99%
[P9764 17:07:19.174 reader.go:172 I] cipd: extracting - 100%
[P9764 17:07:19.905 deployer.go:228 I] Successfully deployed infra/depot_tools/g
it_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9764 17:07:19.909 client.go:1274 I] All changes applied.
Traceback (most recent call last):
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 193, in <module>
    sys.exit(main(sys.argv[1:]))
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 185, in main
    install_git(args, git_version, git_directory)
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 115, in install_git
    '-Directory="%s"' % git_directory.replace('\\', '\\\\'),
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 26, in _check_call
    subprocess.check_call(argv, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
