### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe | building on linux

### ISSUE THREAD

**Issue by MohammadRostamiorg** [telegramdesktop/tdesktop#27650]
### Steps to reproduce

1 . clone repo
2. cd tdesktop 
3. ./Telegram/build/prepare/linux.sh

### Expected behaviour

build telegram 

### Actual behaviour

Installing dependencies from lock file

```
No dependencies to install or update

Installing the current project: centos_env (0.1.0)
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Mammad/Documents/Projects/tdesktop/Telegram/build/docker/centos_env/gen_dockerfile.py", line 10, in main
    print(Environment(loader=FileSystemLoader(dirname(__file__))).get_template("Dockerfile").render(
BrokenPipeError: [Errno 32] Broken pipe
```

### Operating system

Arch Linux

### Version of Telegram Desktop

git dev

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Looks like you haven't installed all components of the Docker according to the error message?
