### ISSUE TITLE
Segmentation fault in telegram-desktop

### ISSUE THREAD

**Issue by ligurio** [telegramdesktop/tdesktop#28438]
### Steps to reproduce

1. open Group info in a chat
2. press on 'three dots'  and open menu
3. choose statistics
4. close a window with statistics
5. press on 'three dots' again

### Expected behaviour

opened menu

### Actual behaviour

Application is closed and coredump was generated

```c++
#0  __memmove_evex_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:708
#1  0x000070674d61cfbe in QImage::copy(QRect const&) const () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#2  0x000070674d61d255 in QImage::detach() () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#3  0x000070674d7e3550 in QPainter::begin(QPaintDevice*) () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#4  0x0000703a4184c47d in QtWaylandClient::QWaylandShmBackingStore::beginPaint(QRegion const&) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6WaylandClient.so.6
#5  0x000070674d7063ff in QBackingStore::beginPaint(QRegion const&) () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#6  0x000070674e972208 in QWidgetRepaintManager::paintAndFlush() () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#7  0x000070674e967090 in QWidget::event(QEvent*) () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#8  0x000056843bda2ea1 in ?? ()
#9  0x000070674e90abc6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#10 0x000056843a1b8526 in ?? ()
#11 0x000070674c6df8fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#12 0x000070674c6e3319 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#13 0x000070674c9b88f7 in ?? () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#14 0x000070674c253d3b in g_main_context_dispatch () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x000070674c2a9258 in ?? () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x000070674c2513e3 in g_main_context_iteration () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x000070674c9b812e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#18 0x000070674c6ebd5b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#19 0x000070674c6e8026 in QCoreApplication::exec() () from /snap/telegram-desktop/5767/usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#20 0x000056843a194989 in ?? ()
#21 0x000056843a194c8d in ?? ()
#22 0x0000568438b23af9 in ?? ()
#23 0x000070674bcafd90 in __libc_start_call_main (main=main@entry=0x568438b23ac0, argc=argc@entry=1, argv=argv@entry=0x7fff72eea3d8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#24 0x000070674bcafe40 in __libc_start_main_impl (main=0x568438b23ac0, argc=1, argv=0x7fff72eea3d8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff72eea3c8) at ../csu/libc-start.c:392
#25 0x0000568438b2ecc5 in ?? ()
```

I've coredumps and I can share it, feel free to ask.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.16.4-1-g77835a43a

### Installation source

Snap

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> ### Version of Telegram Desktop
> 
> 4.16.4-1-g77835a43a

That's VERY outdated

**Comment by ligurio** [comment]
Seems works fine on updated version.
