### ISSUE TITLE
gyp\refresh.bat error~

### ISSUE THREAD

**Issue by kenan2677** [telegramdesktop/tdesktop#3225]
C:\TBuild\tdesktop\Telegram>gyp\refresh.bat
Traceback (most recent call last):
  File "C:\TBuild\Libraries\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\TBuild\Libraries\gyp\pylib\gyp\__init__.py", line 37
    print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                         ^
SyntaxError: invalid syntax
FAILED

**Comment by john-preston** [comment]
@kenan2677 Perhaps you need to use some other version of Python.

**Comment by kenan2677** [comment]
@john-preston thanks python 2.27 OK~~~
