### ISSUE TITLE
final compile error

### ISSUE THREAD

**Issue by majidjan** [telegramdesktop/tdesktop#3344]
Hi sir
I'm struggling with telegramDesktop for several days on win7 64 .
I used [dependencies_windows](https://github.com/telegramdesktop/dependencies_windows)  after failing to compile one by one .
in final step i got this error "MSB3073	The command "call ninja.exe -C out\Release\ exited with code 1.	"
after struggling with ninja and MSB3037 , i found out ninja is running and error raised from another part .
it's my compile log.
i think i have kind of problem with "Command 'C:\Python27\python.exe" .
please help me
thanks in advance

```
1>------ Rebuild All started: Project: Telegram, Configuration: Release Win32 ------
2>------ Rebuild All started: Project: Updater, Configuration: Release Win32 ------
1>  Cleaning... 0 files.
2>  Cleaning... 0 files.
1>  ninja: Entering directory `out\Release\'
1>  [1/762] RC ..\..\Telegram\Resources\winrc\Updater.rc
1>  FAILED: Resources/winrc/Updater.Updater.res
1>  C:\Python27\python.exe gyp-win-tool rc-wrapper environment.x86 rc.exe -DWIN32 -D_WINDOWS -D_UNICODE -DUNICODE -DHAVE_STDINT_H -DZLIB_WINAPI -D_SCL_SECURE_NO_WARNINGS -D_USING_V110_SDK71_ -DNDEBUG -I..\..\Telegram\SourceFiles /I..\..\Telegram\gyp /foResources\winrc\Updater.Updater.res ..\..\Telegram\Resources\winrc\Updater.rc
1>  'rc.exe' is not recognized as an internal or external command,
1>
1>  operable program or batch file.
1>
1>  [2/762] RULE Moc-ing checked_utf8_string.h..
1>  [3/762] RULE Moc-ing basic_tokenized_file.h..
1>  [4/762] RULE Moc-ing clean_file_reader.h..
1>  [5/762] RULE Moc-ing clean_file.h..
1>  [6/762] RULE Moc-ing cpp_file.h..
1>  [7/762] RULE Moc-ing const_utf8_string.h..
1>  [8/762] RULE Moc-ing generator.h..
1>  [9/762] RULE Moc-ing logging.h..
1>  [10/762] RULE Moc-ing module.h..
1>  [11/762] RULE Moc-ing options.h..
1>  [12/762] RULE Moc-ing parsed_file.h..
1>  [13/762] RULE Moc-ing processor.h..
1>  [14/762] RULE Moc-ing structure_types.h..
1>  [15/762] STAMP obj\codegen_style.actions_rules_copies.stamp
1>  [16/762] RULE Moc-ing basic_tokenized_file.h..
2>  ninja: Entering directory `out\Release\'
2>  [1/3] RC ..\..\Telegram\Resources\winrc\Updater.rc
2>  FAILED: Resources/winrc/Updater.Updater.res
2>  C:\Python27\python.exe gyp-win-tool rc-wrapper environment.x86 rc.exe -DWIN32 -D_WINDOWS -D_UNICODE -DUNICODE -DHAVE_STDINT_H -DZLIB_WINAPI -D_SCL_SECURE_NO_WARNINGS -D_USING_V110_SDK71_ -DNDEBUG -I..\..\Telegram\SourceFiles /I..\..\Telegram\gyp /foResources\winrc\Updater.Updater.res ..\..\Telegram\Resources\winrc\Updater.rc
2>  'rc.exe' is not recognized as an internal or external command,
2>
2>  operable program or batch file.
2>
1>  [17/762] CXX SourceFiles\_other\Updater.updater.obj
2>  [2/3] CXX SourceFiles\_other\Updater.updater.obj
2>  ninja: build stopped: cannot make progress due to previous errors.
2>D:\TBuild\tdesktop\Updater.vcxproj(124,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 Updater" exited with code 1.
3>------ Rebuild All started: Project: codegen_emoji, Configuration: Release Win32 ------
3>  Cleaning... 0 files.
1>  [18/762] CXX SourceFiles\codegen\common\codegen_style.checked_utf8_string.obj
1>  [19/762] CXX SourceFiles\codegen\common\codegen_style.basic_tokenized_file.obj
3>  ninja: Entering directory `out\Release\'
3>  [1/13] RULE Moc-ing logging.h..
3>  [2/13] RULE Moc-ing cpp_file.h..
3>  [3/13] RULE Moc-ing data.h..
3>  [4/13] RULE Moc-ing generator.h..
3>  [5/13] RULE Moc-ing options.h..
3>  [6/13] STAMP obj\codegen_emoji.actions_rules_copies.stamp
1>  [20/762] CXX SourceFiles\codegen\common\codegen_style.clean_file.obj
1>  [21/762] CXX SourceFiles\codegen\common\codegen_style.logging.obj
1>  [22/762] CXX SourceFiles\codegen\common\codegen_style.cpp_file.obj
3>  [7/13] CXX SourceFiles\codegen\common\codegen_emoji.cpp_file.obj
3>  [8/13] CXX SourceFiles\codegen\common\codegen_emoji.logging.obj
3>  [9/13] CXX SourceFiles\codegen\emoji\codegen_emoji.data.obj
1>  [23/762] CXX SourceFiles\codegen\style\codegen_style.main.obj
1>  [24/762] CXX SourceFiles\codegen\style\codegen_style.module.obj
3>  [10/13] CXX SourceFiles\codegen\emoji\codegen_emoji.options.obj
3>  [11/13] CXX SourceFiles\codegen\emoji\codegen_emoji.main.obj
1>  [25/762] CXX SourceFiles\codegen\style\codegen_style.generator.obj
3>  [12/13] CXX SourceFiles\codegen\emoji\codegen_emoji.generator.obj
3>  [13/13] LINK_EMBED codegen_emoji.exe
1>  [26/762] CXX SourceFiles\codegen\style\codegen_style.options.obj
3>  FAILED: codegen_emoji.exe codegen_emoji.exe.pdb
3>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_emoji.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_emoji.exe @codegen_emoji.exe.rsp" 1 mt.exe rc.exe "obj\codegen_emoji.codegen_emoji.exe.intermediate.manifest" obj\codegen_emoji.codegen_emoji.exe.generated.manifest
3>  'mt.exe' is not recognized as an internal or external command,
3>
3>  operable program or batch file.
3>
3>  Traceback (most recent call last):
3>
3>    File "gyp-win-tool", line 323, in <module>
3>
3>      sys.exit(main(sys.argv[1:]))
3>
3>    File "gyp-win-tool", line 29, in main
3>
3>      exit_code = executor.Dispatch(args)
3>
3>    File "gyp-win-tool", line 71, in Dispatch
3>
3>      return getattr(self, method)(*args[1:])
3>
3>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
3>
3>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
3>
3>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
3>
3>      raise CalledProcessError(retcode, cmd)
3>
3>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_emoji.codegen_emoji.exe.generated.manifest -out:codegen_emoji.exe.manifest' returned non-zero exit status 1
3>
3>  ninja: build stopped: cannot make progress due to previous errors.
3>D:\TBuild\tdesktop\codegen_emoji.vcxproj(126,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 codegen_emoji" exited with code 1.
4>------ Rebuild All started: Project: codegen_lang, Configuration: Release Win32 ------
4>  Cleaning... 0 files.
4>  ninja: Entering directory `out\Release\'
4>  [1/23] RULE Moc-ing checked_utf8_string.h..
4>  [2/23] RULE Moc-ing clean_file.h..
4>  [3/23] RULE Moc-ing basic_tokenized_file.h..
4>  [4/23] RULE Moc-ing clean_file_reader.h..
4>  [5/23] RULE Moc-ing logging.h..
1>  [27/762] CXX SourceFiles\codegen\style\codegen_style.parsed_file.obj
4>  [6/23] RULE Moc-ing const_utf8_string.h..
4>  [7/23] RULE Moc-ing cpp_file.h..
1>  [28/762] RULE Moc-ing checked_utf8_string.h..
4>  [8/23] RULE Moc-ing options.h..
4>  [9/23] RULE Moc-ing generator.h..
4>  [10/23] RULE Moc-ing parsed_file.h..
4>  [11/23] RULE Moc-ing processor.h..
1>  [29/762] RULE Moc-ing clean_file.h..
4>  [12/23] STAMP obj\codegen_lang.actions_rules_copies.stamp
1>  [30/762] RULE Moc-ing clean_file_reader.h..
1>  [31/762] RULE Moc-ing const_utf8_string.h..
4>  [13/23] CXX SourceFiles\codegen\common\codegen_lang.checked_utf8_string.obj
4>  [14/23] CXX SourceFiles\codegen\common\codegen_lang.basic_tokenized_file.obj
1>  [32/762] CXX SourceFiles\codegen\style\codegen_style.structure_types.obj
1>  [33/762] RULE Moc-ing cpp_file.h..
1>  [34/762] RULE Moc-ing logging.h..
1>  [35/762] RULE Moc-ing generator.h..
4>  [15/23] CXX SourceFiles\codegen\common\codegen_lang.clean_file.obj
1>  [36/762] RULE Moc-ing options.h..
1>  [37/762] RULE Moc-ing parsed_file.h..
1>  [38/762] CXX SourceFiles\codegen\style\codegen_style.processor.obj
1>  [39/762] RULE Moc-ing basic_tokenized_file.h..
1>  [40/762] RULE Moc-ing processor.h..
1>  [41/762] STAMP obj\codegen_numbers.actions_rules_copies.stamp
1>  [42/762] RULE Moc-ing checked_utf8_string.h..
1>  [43/762] LINK_EMBED codegen_style.exe
1>  FAILED: codegen_style.exe codegen_style.exe.pdb
1>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_style.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_style.exe @codegen_style.exe.rsp" 1 mt.exe rc.exe "obj\codegen_style.codegen_style.exe.intermediate.manifest" obj\codegen_style.codegen_style.exe.generated.manifest
1>  'mt.exe' is not recognized as an internal or external command,
1>
1>  operable program or batch file.
1>
1>  Traceback (most recent call last):
1>
1>    File "gyp-win-tool", line 323, in <module>
1>
1>      sys.exit(main(sys.argv[1:]))
1>
1>    File "gyp-win-tool", line 29, in main
1>
1>      exit_code = executor.Dispatch(args)
1>
1>    File "gyp-win-tool", line 71, in Dispatch
1>
1>      return getattr(self, method)(*args[1:])
1>
1>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
1>
1>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
1>
1>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
1>
1>      raise CalledProcessError(retcode, cmd)
1>
1>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_style.codegen_style.exe.generated.manifest -out:codegen_style.exe.manifest' returned non-zero exit status 1
1>
4>  [16/23] CXX SourceFiles\codegen\common\codegen_lang.cpp_file.obj
4>  [17/23] CXX SourceFiles\codegen\common\codegen_lang.logging.obj
1>  [44/762] CXX SourceFiles\codegen\common\codegen_numbers.checked_utf8_string.obj
1>  [45/762] CXX SourceFiles\codegen\common\codegen_numbers.basic_tokenized_file.obj
1>  [46/762] CXX SourceFiles\codegen\common\codegen_numbers.clean_file.obj
1>  [47/762] CXX SourceFiles\codegen\common\codegen_numbers.logging.obj
1>  [48/762] CXX SourceFiles\codegen\common\codegen_numbers.cpp_file.obj
4>  [18/23] CXX SourceFiles\codegen\lang\codegen_lang.generator.obj
4>  [19/23] CXX SourceFiles\codegen\lang\codegen_lang.main.obj
1>  [49/762] CXX SourceFiles\codegen\numbers\codegen_numbers.generator.obj
4>  [20/23] CXX SourceFiles\codegen\lang\codegen_lang.options.obj
1>  [50/762] CXX SourceFiles\codegen\numbers\codegen_numbers.main.obj
1>  [51/762] CXX SourceFiles\codegen\numbers\codegen_numbers.options.obj
1>  [52/762] RULE Moc-ing clean_file.h..
1>  [53/762] RULE Moc-ing clean_file_reader.h..
1>  [54/762] RULE Moc-ing const_utf8_string.h..
1>  [55/762] RULE Moc-ing cpp_file.h..
1>  [56/762] RULE Moc-ing logging.h..
1>  [57/762] RULE Moc-ing generator.h..
1>  [58/762] RULE Moc-ing options.h..
1>  [59/762] RULE Moc-ing parsed_file.h..
4>  [21/23] CXX SourceFiles\codegen\lang\codegen_lang.parsed_file.obj
1>  [60/762] RULE Moc-ing processor.h..
1>  [61/762] STAMP obj\codegen_lang.actions_rules_copies.stamp
4>  [22/23] CXX SourceFiles\codegen\lang\codegen_lang.processor.obj
4>  [23/23] LINK_EMBED codegen_lang.exe
4>  FAILED: codegen_lang.exe codegen_lang.exe.pdb
4>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_lang.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_lang.exe @codegen_lang.exe.rsp" 1 mt.exe rc.exe "obj\codegen_lang.codegen_lang.exe.intermediate.manifest" obj\codegen_lang.codegen_lang.exe.generated.manifest
4>  'mt.exe' is not recognized as an internal or external command,
4>
4>  operable program or batch file.
4>
1>  [62/762] CXX SourceFiles\codegen\numbers\codegen_numbers.parsed_file.obj
4>  Traceback (most recent call last):
4>
4>    File "gyp-win-tool", line 323, in <module>
4>
4>      sys.exit(main(sys.argv[1:]))
4>
4>    File "gyp-win-tool", line 29, in main
4>
4>      exit_code = executor.Dispatch(args)
4>
4>    File "gyp-win-tool", line 71, in Dispatch
4>
4>      return getattr(self, method)(*args[1:])
4>
4>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
4>
4>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
4>
4>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
4>
4>      raise CalledProcessError(retcode, cmd)
4>
4>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_lang.codegen_lang.exe.generated.manifest -out:codegen_lang.exe.manifest' returned non-zero exit status 1
4>
4>  ninja: build stopped: cannot make progress due to previous errors.
4>ninja : warning : premature end of file; recovering
4>D:\TBuild\tdesktop\codegen_lang.vcxproj(136,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 codegen_lang" exited with code 1.
5>------ Rebuild All started: Project: codegen_numbers, Configuration: Release Win32 ------
1>  [63/762] CXX SourceFiles\codegen\numbers\codegen_numbers.processor.obj
5>  Cleaning... 23 files.
1>  [64/762] LINK_EMBED codegen_numbers.exe
1>  FAILED: codegen_numbers.exe codegen_numbers.exe.pdb
1>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_numbers.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_numbers.exe @codegen_numbers.exe.rsp" 1 mt.exe rc.exe "obj\codegen_numbers.codegen_numbers.exe.intermediate.manifest" obj\codegen_numbers.codegen_numbers.exe.generated.manifest
1>  'mt.exe' is not recognized as an internal or external command,
1>
5>  ninja: Entering directory `out\Release\'
1>  operable program or batch file.
1>
1>  Traceback (most recent call last):
1>
1>    File "gyp-win-tool", line 323, in <module>
1>
1>      sys.exit(main(sys.argv[1:]))
1>
1>    File "gyp-win-tool", line 29, in main
1>
1>      exit_code = executor.Dispatch(args)
1>
1>    File "gyp-win-tool", line 71, in Dispatch
1>
1>      return getattr(self, method)(*args[1:])
1>
1>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
1>
1>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
1>
1>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
1>
1>      raise CalledProcessError(retcode, cmd)
1>
1>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_numbers.codegen_numbers.exe.generated.manifest -out:codegen_numbers.exe.manifest' returned non-zero exit status 1
1>
5>  [1/23] RULE Moc-ing checked_utf8_string.h..
5>  [2/23] RULE Moc-ing clean_file.h..
5>  [3/23] RULE Moc-ing basic_tokenized_file.h..
5>  [4/23] RULE Moc-ing const_utf8_string.h..
5>  [5/23] RULE Moc-ing clean_file_reader.h..
5>  [6/23] RULE Moc-ing logging.h..
5>  [7/23] RULE Moc-ing cpp_file.h..
5>  [8/23] RULE Moc-ing generator.h..
5>  [9/23] RULE Moc-ing parsed_file.h..
5>  [10/23] RULE Moc-ing options.h..
5>  [11/23] RULE Moc-ing processor.h..
5>  [12/23] STAMP obj\codegen_numbers.actions_rules_copies.stamp
1>  [65/762] CXX SourceFiles\codegen\common\codegen_lang.basic_tokenized_file.obj
1>  [66/762] CXX SourceFiles\codegen\common\codegen_lang.clean_file.obj
5>  [13/23] CXX SourceFiles\codegen\common\codegen_numbers.basic_tokenized_file.obj
1>  [67/762] CXX SourceFiles\codegen\common\codegen_lang.checked_utf8_string.obj
5>  [14/23] CXX SourceFiles\codegen\common\codegen_numbers.checked_utf8_string.obj
5>  [15/23] CXX SourceFiles\codegen\common\codegen_numbers.clean_file.obj
1>  [68/762] CXX SourceFiles\codegen\common\codegen_lang.logging.obj
1>  [69/762] CXX SourceFiles\codegen\common\codegen_lang.cpp_file.obj
5>  [16/23] CXX SourceFiles\codegen\common\codegen_numbers.cpp_file.obj
5>  [17/23] CXX SourceFiles\codegen\common\codegen_numbers.logging.obj
1>  [70/762] CXX SourceFiles\codegen\lang\codegen_lang.main.obj
5>  [18/23] CXX SourceFiles\codegen\numbers\codegen_numbers.generator.obj
1>  [71/762] CXX SourceFiles\codegen\lang\codegen_lang.generator.obj
5>  [19/23] CXX SourceFiles\codegen\numbers\codegen_numbers.options.obj
1>  [72/762] CXX SourceFiles\codegen\lang\codegen_lang.options.obj
5>  [20/23] CXX SourceFiles\codegen\numbers\codegen_numbers.main.obj
1>  [73/762] RULE Moc-ing cpp_file.h..
1>  [74/762] RULE Moc-ing logging.h..
1>  [75/762] RULE Moc-ing data.h..
1>  [76/762] RULE Moc-ing generator.h..
1>  [77/762] RULE Moc-ing options.h..
1>  [78/762] STAMP obj\codegen_emoji.actions_rules_copies.stamp
5>  [21/23] CXX SourceFiles\codegen\numbers\codegen_numbers.parsed_file.obj
1>  [79/762] CXX SourceFiles\codegen\lang\codegen_lang.parsed_file.obj
5>  [22/23] CXX SourceFiles\codegen\numbers\codegen_numbers.processor.obj
1>  [80/762] CXX SourceFiles\codegen\lang\codegen_lang.processor.obj
1>  [81/762] CXX SourceFiles\codegen\common\codegen_emoji.cpp_file.obj
5>  [23/23] LINK_EMBED codegen_numbers.exe
5>  FAILED: codegen_numbers.exe codegen_numbers.exe.pdb
5>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_numbers.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_numbers.exe @codegen_numbers.exe.rsp" 1 mt.exe rc.exe "obj\codegen_numbers.codegen_numbers.exe.intermediate.manifest" obj\codegen_numbers.codegen_numbers.exe.generated.manifest
5>  'mt.exe' is not recognized as an internal or external command,
5>
5>  operable program or batch file.
5>
5>  Traceback (most recent call last):
5>
5>    File "gyp-win-tool", line 323, in <module>
5>
5>      sys.exit(main(sys.argv[1:]))
5>
5>    File "gyp-win-tool", line 29, in main
5>
5>      exit_code = executor.Dispatch(args)
5>
5>    File "gyp-win-tool", line 71, in Dispatch
5>
5>      return getattr(self, method)(*args[1:])
5>
5>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
5>
5>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
5>
5>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
5>
5>      raise CalledProcessError(retcode, cmd)
5>
5>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_numbers.codegen_numbers.exe.generated.manifest -out:codegen_numbers.exe.manifest' returned non-zero exit status 1
5>
5>  ninja: build stopped: cannot make progress due to previous errors.
5>ninja : warning : premature end of file; recovering
5>D:\TBuild\tdesktop\codegen_numbers.vcxproj(136,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 codegen_numbers" exited with code 1.
6>------ Rebuild All started: Project: codegen_style, Configuration: Release Win32 ------
1>  [82/762] LINK_EMBED codegen_lang.exe
1>  FAILED: codegen_lang.exe codegen_lang.exe.pdb
1>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_lang.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_lang.exe @codegen_lang.exe.rsp" 1 mt.exe rc.exe "obj\codegen_lang.codegen_lang.exe.intermediate.manifest" obj\codegen_lang.codegen_lang.exe.generated.manifest
1>  'mt.exe' is not recognized as an internal or external command,
1>
1>  operable program or batch file.
1>
1>  Traceback (most recent call last):
6>  Cleaning... 27 files.
1>
1>    File "gyp-win-tool", line 323, in <module>
1>
1>      sys.exit(main(sys.argv[1:]))
1>
1>    File "gyp-win-tool", line 29, in main
1>
1>      exit_code = executor.Dispatch(args)
1>
1>    File "gyp-win-tool", line 71, in Dispatch
1>
1>      return getattr(self, method)(*args[1:])
1>
1>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
1>
1>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
1>
1>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
6>  ninja: Entering directory `out\Release\'
1>
6>  [1/27] RULE Moc-ing basic_tokenized_file.h..
1>      raise CalledProcessError(retcode, cmd)
1>
1>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_lang.codegen_lang.exe.generated.manifest -out:codegen_lang.exe.manifest' returned non-zero exit status 1
1>
6>  [2/27] RULE Moc-ing checked_utf8_string.h..
6>  [3/27] RULE Moc-ing clean_file_reader.h..
6>  [4/27] RULE Moc-ing clean_file.h..
6>  [5/27] RULE Moc-ing const_utf8_string.h..
6>  [6/27] RULE Moc-ing logging.h..
6>  [7/27] RULE Moc-ing generator.h..
6>  [8/27] RULE Moc-ing cpp_file.h..
6>  [9/27] RULE Moc-ing parsed_file.h..
6>  [10/27] RULE Moc-ing options.h..
6>  [11/27] RULE Moc-ing module.h..
6>  [12/27] RULE Moc-ing processor.h..
6>  [13/27] RULE Moc-ing structure_types.h..
6>  [14/27] STAMP obj\codegen_style.actions_rules_copies.stamp
1>  [83/762] CXX SourceFiles\codegen\common\codegen_emoji.logging.obj
6>  [15/27] CXX SourceFiles\codegen\common\codegen_style.clean_file.obj
1>  [84/762] CXX SourceFiles\codegen\emoji\codegen_emoji.data.obj
1>  [85/762] CXX SourceFiles\codegen\emoji\codegen_emoji.generator.obj
6>  [16/27] CXX SourceFiles\codegen\common\codegen_style.checked_utf8_string.obj
6>  [17/27] CXX SourceFiles\codegen\common\codegen_style.basic_tokenized_file.obj
1>  [86/762] CXX SourceFiles\codegen\emoji\codegen_emoji.main.obj
6>  [18/27] CXX SourceFiles\codegen\common\codegen_style.cpp_file.obj
1>  [87/762] CXX SourceFiles\codegen\emoji\codegen_emoji.options.obj
6>  [19/27] CXX SourceFiles\codegen\common\codegen_style.logging.obj
1>  [88/762] LINK_EMBED codegen_emoji.exe
1>  FAILED: codegen_emoji.exe codegen_emoji.exe.pdb
1>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_emoji.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_emoji.exe @codegen_emoji.exe.rsp" 1 mt.exe rc.exe "obj\codegen_emoji.codegen_emoji.exe.intermediate.manifest" obj\codegen_emoji.codegen_emoji.exe.generated.manifest
1>  'mt.exe' is not recognized as an internal or external command,
1>
1>  operable program or batch file.
1>
1>  Traceback (most recent call last):
1>
1>    File "gyp-win-tool", line 323, in <module>
1>
1>      sys.exit(main(sys.argv[1:]))
1>
1>    File "gyp-win-tool", line 29, in main
1>
1>      exit_code = executor.Dispatch(args)
1>
1>    File "gyp-win-tool", line 71, in Dispatch
1>
1>      return getattr(self, method)(*args[1:])
1>
1>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
1>
1>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
1>
1>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
1>
1>      raise CalledProcessError(retcode, cmd)
1>
1>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_emoji.codegen_emoji.exe.generated.manifest -out:codegen_emoji.exe.manifest' returned non-zero exit status 1
1>
1>  ninja: build stopped: cannot make progress due to previous errors.
1>ninja : warning : premature end of file; recovering
1>D:\TBuild\tdesktop\Telegram.vcxproj(978,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 Telegram" exited with code 1.
6>  [20/27] CXX SourceFiles\codegen\style\codegen_style.generator.obj
6>  [21/27] CXX SourceFiles\codegen\style\codegen_style.main.obj
6>  [22/27] CXX SourceFiles\codegen\style\codegen_style.module.obj
6>  [23/27] CXX SourceFiles\codegen\style\codegen_style.options.obj
6>  [24/27] CXX SourceFiles\codegen\style\codegen_style.processor.obj
6>  [25/27] CXX SourceFiles\codegen\style\codegen_style.parsed_file.obj
6>  [26/27] CXX SourceFiles\codegen\style\codegen_style.structure_types.obj
6>  [27/27] LINK_EMBED codegen_style.exe
6>  FAILED: codegen_style.exe codegen_style.exe.pdb
6>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_style.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_style.exe @codegen_style.exe.rsp" 1 mt.exe rc.exe "obj\codegen_style.codegen_style.exe.intermediate.manifest" obj\codegen_style.codegen_style.exe.generated.manifest
6>  'mt.exe' is not recognized as an internal or external command,
6>
6>  operable program or batch file.
6>
6>  Traceback (most recent call last):
6>
6>    File "gyp-win-tool", line 323, in <module>
6>
6>      sys.exit(main(sys.argv[1:]))
6>
6>    File "gyp-win-tool", line 29, in main
6>
6>      exit_code = executor.Dispatch(args)
6>
6>    File "gyp-win-tool", line 71, in Dispatch
6>
6>      return getattr(self, method)(*args[1:])
6>
6>    File "gyp-win-tool", line 170, in ExecLinkWithManifests
6>
6>      '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
6>
6>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
6>
6>      raise CalledProcessError(retcode, cmd)
6>
6>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x86 mt.exe -nologo -manifest obj\codegen_style.codegen_style.exe.generated.manifest -out:codegen_style.exe.manifest' returned non-zero exit status 1
6>
6>  ninja: build stopped: cannot make progress due to previous errors.
6>ninja : warning : premature end of file; recovering
6>D:\TBuild\tdesktop\codegen_style.vcxproj(140,5): error MSB3073: The command "call ninja.exe -C out\Release\ -k0 codegen_style" exited with code 1.
========== Rebuild All: 0 succeeded, 6 failed, 0 skipped ==========

```

**Comment by stek29** [comment]
> `'rc.exe' is not recognized as an internal or external command`
Is this normal?

**Comment by majidjan** [comment]
hi stek29
i don't think so ... maybe it's the problem . thanks a lot

**Comment by majidjan** [comment]
Hi all
anybody has any idea what is my problem ?

**Comment by OrBin** [comment]
@majidjan could you solve it? I get this error too when building Release configuration, but can build successfully Debug configuration.

**Comment by auchri** [comment]
Maybe that is the solution: https://stackoverflow.com/a/42192878/4752807
