### ISSUE TITLE
Telegram crashes during Call with actions with sound and some other things

### ISSUE THREAD

**Issue by Oggesus** [telegramdesktop/tdesktop#3595]
1. Launch Telegram Calls.
2. Open Browser/Change volume/Play video/Music. (seldom) while scrolling dialog fast\scrolling my gifs list

Telegram crashes (not with 100% chance, but these actions can provoke crash). Sometimes client gently closes call with message about audio error, sometimes freeze client with call window (with emoji), sometimes (often) crashes Telegram without dumps in dump folder.

Lubuntu/Xubuntu (clean)

Telegram Desktop 1.1.7

```
(gdb) Quit
(gdb) bt f
#0  0xb7fd9ce5 in __kernel_vsyscall ()
No symbol table info available.
#1  0xb7aa6ea9 in __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = <optimized out>
        resultvar = <optimized out>
        pid = 16174
        selftid = 16218
#2  0xb7aa8407 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0xb7a88148, sa_sigaction = 0xb7a88148}, sa_mask = {
            __val = {3081669401, 213065716, 3086895760, 134868660, 5, 3087005976, 213067284, 3086915778, 
              3087006416, 3078951184, 1, 5, 0, 166176776, 219648544, 219648556, 2210447492, 0, 
              3087003648, 135616020, 3083001024, 3081604815, 3083001024, 3081245112, 2210447528, 
              215463492, 3086915595, 224427764, 2210456172, 220071808, 2210447528, 3086942256}}, 
          sa_flags = 0, sa_restorer = 0xb7aa82b0 <__GI_abort>}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#3  0x08aaff00 in rtc::FatalMessage::~FatalMessage() ()
No symbol table info available.
#4  0x08ac39dc in webrtc::BlockBuffer::ExtractExtendedBlock(float*) ()
No symbol table info available.
#5  0x08ac9019 in webrtc::WebRtcAec_ProcessFrames(webrtc::AecCore*, float const* const*, unsigned int, unsigned int, int, float* const*) ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#6  0x08ab2ca0 in ?? ()
No symbol table info available.
#7  0x08ab236a in webrtc::WebRtcAec_Process(void*, float const* const*, unsigned int, float* const*, unsigned int, short, int) ()
No symbol table info available.
#8  0x08aab992 in tgvoip::EchoCanceller::ProcessInput(unsigned char*, unsigned char*, unsigned int) ()
No symbol table info available.
#9  0x08aaf5a8 in tgvoip::OpusEncoder::RunThread() ()
No symbol table info available.
#10 0x08aaf483 in tgvoip::OpusEncoder::StartThread(void*) ()
No symbol table info available.
#11 0xb7caa295 in start_thread (arg=0x83c0eb40) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x83c0eb40
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1211375616, 0, 4001536, -2084510872, 763339823, 
                972976711}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
---Type <return> to continue, or q <return> to quit---
#12 0xb7b6205e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:114
No locals.
(gdb) 
```

```
Fatal error in /home/antanubis/TBuild/tdesktop/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc/modules/audio_processing/aec/aec_core.cc, line 205
# Check failed: 0 < AvaliableSpace() (0 vs. 0)
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3412

**Comment by Oggesus** [comment]
> #3412
Voice Call crashes NOT when starting, so I think that's another problem.

**Comment by Aokromes** [comment]
@Oggesus can you try on 1.2.6? #4195 mentions it fixes voicecall crash.

**Comment by Aokromes** [comment]
@Oggesus Try on 1.3.14 :)

**Comment by Aokromes** [comment]
no answer for more than a year. closing.
