### ISSUE TITLE
Crash on Arch Linux on startup (KDE)

### ISSUE THREAD

**Issue by FallenAngel97** [telegramdesktop/tdesktop#5016]
### Steps to reproduce
1. Launch telegram-desktop from Arch linux

### Expected behaviour
The application should launch & show GUI

### Actual behaviour
It crashes and calls dr konqi

### Configuration
Linux ArchHost 4.17.9-1-ARCH #1 SMP PREEMPT Sun Jul 22 20:23:36 UTC 2018 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.3.10
**Used theme**:
Deafult

<details><summary><b>Logs</b>:</summary>
Application: telegram-desktop (telegram-desktop), signal: Aborted
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f813f3b7d40 (LWP 2254))]

Thread 7 (Thread 0x7f8105b38700 (LWP 2265)):
#0  0x00007f8139679514 in read () at /usr/lib/libpthread.so.0
#1  0x00007f8139918ed1 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d2ff8 in g_main_context_check () at /usr/lib/libglib-2.0.so.0
#3  0x00007f81398d34c6 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f81398d363e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#5  0x00007f813a823054 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007f813a7ce94c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#7  0x00007f813a617a99 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#8  0x00007f813a621b45 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f8106339700 (LWP 2264)):
#0  0x00007f8138a64ea9 in poll () at /usr/lib/libc.so.6
#1  0x00007f81398d3523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d363e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f813a823054 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f813a7ce94c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f813a617a99 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f813a621b45 in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f8106b3a700 (LWP 2263)):
#0  0x00007f8139679514 in read () at /usr/lib/libpthread.so.0
#1  0x00007f8139918ed1 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d2ff8 in g_main_context_check () at /usr/lib/libglib-2.0.so.0
#3  0x00007f81398d34c6 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f81398d363e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#5  0x00007f813a823054 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007f813a7ce94c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#7  0x00007f813a617a99 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#8  0x00007f813a621b45 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f8107b1e700 (LWP 2258)):
#0  0x00007f8138a64ea9 in poll () at /usr/lib/libc.so.6
#1  0x00007f81398d3523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d38e2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007f8115548348 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f81398fba2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f810831f700 (LWP 2257)):
#0  0x00007f813991a2f4 in g_mutex_unlock () at /usr/lib/libglib-2.0.so.0
#1  0x00007f81398d34dd in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d363e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f81398d3692 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f81398fba2a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f8110bb0700 (LWP 2256)):
#0  0x00007f8138a64ea9 in poll () at /usr/lib/libc.so.6
#1  0x00007f81398d3523 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f81398d363e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f813a823054 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f813a7ce94c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f813a617a99 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f813ac73976 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007f813a621b45 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f8139670075 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f8138a6f53f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f813f3b7d40 (LWP 2254)):
[KCrash Handler]
#6  0x00007f81389ad86b in raise () at /usr/lib/libc.so.6
#7  0x00007f813899840e in abort () at /usr/lib/libc.so.6
#8  0x0000558ca63d089e in  ()
#9  0x0000558ca6cadfe9 in Window::MainWindow::init() ()
#10 0x0000558ca6e1c801 in Messenger::Messenger(gsl::not_null<Core::Launcher*>) ()
#11 0x0000558ca6d99ec4 in Application::createMessenger() ()
#12 0x0000558ca6d9a270 in Sandbox::launch() ()
#13 0x0000558ca6d9af66 in Application::socketError(QLocalSocket::LocalSocketError) ()
#14 0x00007f813a7f9afc in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#15 0x00007f813bfdbac2 in QLocalSocket::error(QLocalSocket::LocalSocketError) () at /usr/lib/libQt5Network.so.5
#16 0x00007f813bfddd2c in  () at /usr/lib/libQt5Network.so.5
#17 0x00007f813bfde75f in  () at /usr/lib/libQt5Network.so.5
#18 0x00007f813bfde8ec in QLocalSocket::connectToServer(QFlags<QIODevice::OpenModeFlag>) () at /usr/lib/libQt5Network.so.5
#19 0x0000558ca6d9aa4c in Application::Application(gsl::not_null<Core::Launcher*>, int&, char**) ()
#20 0x0000558ca65b8b50 in Core::Launcher::executeApplication() ()
#21 0x0000558ca65b8c69 in Core::Launcher::exec() ()
#22 0x0000558ca63b23e4 in main ()

</details>

**Comment by FallenAngel97** [comment]
I've found a reason. It crashes, when QtCurve is enabled. Anyone have suggestions how to handle this?

**Comment by FallenAngel97** [comment]
Seems strange, but switching from [telegram-desktop](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/) to  [telegram-desktop-bin](https://aur.archlinux.org/packages/telegram-desktop-bin/) actually works. But I need to prepend it with _FONTCONFIG_FILE_ directive.
