### ISSUE TITLE
Segment fault in Archlinux

### ISSUE THREAD

**Issue by zhustec** [telegramdesktop/tdesktop#5221]
### Steps to reproduce
1. Just click Telegram icon or run telegram-desktop from terminal

### Expected behaviour
Run correctly

### Actual behaviour
Exited after 5 seconds, produce 'Segment Fault error'

### Configuration
Linux 4.18.10-arch1-1-ARCH Archlinux

**Version of Telegram Desktop:** See logs below

**Used theme**: No

<details><summary><b>Logs</b>:</summary>
<pre>
[2018.10.03 09:30:14] Launched version: 1004000, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2018.10.03 09:30:14] Executable dir: /usr/bin/, name: telegram-desktop
[2018.10.03 09:30:14] Initial working dir: /home/zhustec/.local/share/TelegramDesktop/
[2018.10.03 09:30:14] Working dir: /home/zhustec/.local/share/TelegramDesktop/
[2018.10.03 09:30:14] Command line: telegram-desktop --help
[2018.10.03 09:30:14] Executable path before check: /usr/bin/telegram-desktop
[2018.10.03 09:30:14] Logs started
[2018.10.03 09:30:14] Connecting local socket to /tmp/c4b6d3bd25eb26f3fc6b26b56f8be0f5-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2018.10.03 09:30:14] Socket connect error 0, starting server and app...
[2018.10.03 09:30:14] Moved logging from '/home/zhustec/.local/share/TelegramDesktop/log_start0.txt' to '/home/zhustec/.local/share/TelegramDesktop/log.txt'!
[2018.10.03 09:30:14] Font Error: could not locate 'Open Sans Semibold' font in ':/gui/fonts/OpenSans-Semibold.ttf'.
[2018.10.03 09:30:14] Could not load 'appindicator3' with version 1 :(
[2018.10.03 09:30:14] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2018.10.03 09:30:14] Getting DE, XDG_CURRENT_DESKTOP: 'KDE'
[2018.10.03 09:30:14] Getting DE, DESKTOP_SESSION: '/usr/share/xsessions/plasma'
[2018.10.03 09:30:14] Getting DE, KDE_SESSION_VERSION: '5'
[2018.10.03 09:30:14] DE: KDE5
[2018.10.03 09:30:14] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2018.10.03 09:30:14] App Info: reading settings...
[2018.10.03 09:30:14] App Info: reading encrypted settings...
[2018.10.03 09:30:14] OpenAL Logging Level: (not set)
[2018.10.03 09:30:14] Audio Playback Devices: OpenAL Soft
[2018.10.03 09:30:14] Audio Playback Default Device: OpenAL Soft
[2018.10.03 09:30:14] Audio Capture Devices: 内置音频 模拟立体声;Monitor of 内置音频 模拟立体声
[2018.10.03 09:30:14] Audio Capture Default Device: 内置音频 模拟立体声
[2018.10.03 09:30:14] App Info: reading map...
[2018.10.03 09:30:14] App Info: reading encrypted map...
[2018.10.03 09:30:14] App Info: reading encrypted user settings...
[2018.10.03 09:30:14] App Info: encrypted user settings read.
[2018.10.03 09:30:14] App Info: reading encrypted mtp data...
[2018.10.03 09:30:14] MTP Info: read keys, current: 0, to destroy: 0
[2018.10.03 09:30:14] Map read time: 6
[2018.10.03 09:30:14] Using Qt tray icon.
[2018.10.03 09:30:14] Tray Icon: Using Qt tray icon, available: [TRUE]
[2018.10.03 09:30:14] Not using Unity Launcher count.
[2018.10.03 09:30:14] HTTP Error: remote host closed - Connection closed
[2018.10.03 09:30:15] HTTP Error: remote host closed - Connection closed
[2018.10.03 09:30:15] HTTP Error: remote host closed - Connection closed
[2018.10.03 09:30:15] HTTP Error: remote host closed - Connection closed
[2018.10.03 09:30:16] HTTP Error: remote host closed - Connection closed
[2018.10.03 09:30:18] HTTP Error: remote host closed - Connection closed
</pre>
</details>

**Comment by john-preston** [comment]
@zhustec Does the version from https://desktop.telegram.org work for you?

**Comment by Aokromes** [comment]
@zhustec if you run the version preston linked i suggest you to install gdb and run:
gdb ./Telegram
run
and on crash
bt
bt full
and pastebin or gist result.

**Comment by zhustec** [comment]
@john-preston Thx, this works fine for me, and after run it, the original one also works, just don't know why.
@Aokromes GDB output is shown below

<details>
<summary>GDB output: </summary>
<pre>
#0  0x00007ffff5cbfca4 in  () at /usr/lib/libQt5Network.so.5
#1  0x00007ffff5cbe59b in  () at /usr/lib/libQt5Network.so.5
#2  0x00007ffff4d39352 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff5717e14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff571f6e1 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff4d0ec39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff4d11ccc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#7  0x00007ffff4d629d4 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff45cf3cf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff45d0f89 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff45d0fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff4d61fc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#12 0x00007ffff4d0d8cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff4b56eb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff4b60f65 in  () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff454aa9d in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007ffff414aa43 in clone () at /usr/lib/libc.so.6
</pre>
</details>

**Comment by zhustec** [comment]
Don't know why, it still crash today, but after I run the upstream Telegram version https://desktop.telegram.org/ , both will work properly.

**Comment by Aokromes** [comment]
I suggest you to close this ticket and report it to archlinux package maintainer.

**Comment by andreasbaumann** [comment]
Just confirmin: works fine on the i686 and pentium4 architecture branches of Archlinux32.
On Manjaro32 there seems to be a Qt5-API-misalignment with telegram. So,
totally a packaging problem in there.
