### ISSUE TITLE
macos build fails

### ISSUE THREAD

**Issue by caffeinum** [telegramdesktop/tdesktop#5512]
### Steps to reproduce
1. Try https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-xcode.md on Mac OS Mojave (?)

A bit related: #5511
### Expected behaviour
Program builds and runs successfully

### Actual behaviour
After the install steps, I run this command,

![image](https://user-images.githubusercontent.com/1909384/50387902-79779380-0718-11e9-85e8-a94f39b0ca30.png)

which results in error:

![image](https://user-images.githubusercontent.com/1909384/50387899-6d8bd180-0718-11e9-85d0-0bcde9f06dac.png)

### Configuration
**Operating system:** Mac OS Mojave 10.14 (18A389)

**Version of Telegram Desktop:** `master`

**Python**: Python 2.7.15

<details><summary><b>Logs</b>:</summary>
<pre>

$ gyp/refresh.sh --api-id 17349 --api-hash 344583e45741c457fe1862106095a5eb
Traceback (most recent call last):
  File "../../../Libraries/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "../../../Libraries/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "../../../Libraries/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "../../../Libraries/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "../../../Libraries/gyp/pylib/gyp/generator/xcode.py", line 1311, in GenerateOutput
    xcode_projects[build_file].Write()
  File "../../../Libraries/gyp/pylib/gyp/generator/xcode.py", line 449, in Write
    self.project_file.Print(output_file)
  File "../../../Libraries/gyp/pylib/gyp/xcodeproj_file.py", line 2962, in Print
    self._PrintObjects(file)
  File "../../../Libraries/gyp/pylib/gyp/xcodeproj_file.py", line 2988, in _PrintObjects
    object.Print(file)
  File "../../../Libraries/gyp/pylib/gyp/xcodeproj_file.py", line 706, in Print
    self.VerifyHasRequiredProperties()
  File "../../../Libraries/gyp/pylib/gyp/xcodeproj_file.py", line 871, in VerifyHasRequiredProperties
    raise KeyError(self.__class__.__name__ + ' requires ' + property)
KeyError: 'PBXFileReference requires path'
[ERROR] Failed generating for format: xcode

</pre>
</details>

## Additional

During the install, one of the dependencies seems to have failed:

```bash
$ cd crashpad/
$ git checkout feb3aa3923
HEAD on feb3aa39 win: Capture memory pointed to by the stack
$ git apply ../../tdesktop/Telegram/Patches/crashpad.diff
$ cd third_party/mini_chromium
$ git clone https://chromium.googlesource.com/chromium/mini_chromium
fatal: «mini_chromium» exists (it's ok, i cloned already)
$ cd mini_chromium
$ git checkout 7c5b0c1ab4
HEAD on 7c5b0c1 Use Gerrit (Polygerrit) for mini_chromium code review
$ git apply ../../../../../tdesktop/Telegram/Patches/mini_chromium.diff
$ cd ../../gtest
$ git clone https://chromium.googlesource.com/external/github.com/google/googletest gtest
fatal: «gtest» exists (it's ok, i cloned already)
$ cd gtest
$ git checkout d62d6c6556
HEAD on d62d6c6 Merge pull request #982 from mbjorge/unused-variable-fix
$ cd ../../..
$ 
$ build/gyp_crashpad.py -Dmac_deployment_target=10.8
$ ninja -C out/Debug
-bash: /Users/caffeinum/tbuild/depot_tools/ninja: No such file or directory
$ ninja -C out/Release
-bash: /Users/caffeinum/tbuild/depot_tools/ninja: No such file or directory
```

I fixed it using 
```bash
brew install ninja
cd BuildPath/Libraries
mkdir depot_tools
ln -s /usr/local/bin/ninja depot_tools/ninja
```

It seems to does not help, though.

**Comment by caffeinum** [comment]
**UPDATE**

This helped a bit:

```bash
cd BuildPath/Libraries
# remove print on 449 line
vim gyp/pylib/gyp/generator/xcode.py
```

```bash
cd ..
mkdir tdesktop/out
```

Then the guide works: 

```bash
cd tdesktop/Telegram
gyp/refresh.sh
```

However, even though script finishes without error, `.xcodeproj` does not open: 

![image](https://user-images.githubusercontent.com/1909384/50388071-e4c36480-071c-11e9-9419-1c3808f70500.png)
