### ISSUE TITLE
Error in export chat history 

### ISSUE THREAD

**Issue by fakhamatia** [telegramdesktop/tdesktop#6670]
For a few days, I want to export a chat history, but I can't.
its containe 3-4GB (120) video and 1-month period.

In middle of download Telegram crash or show this error.
I test telegram 1.8.16 Windows 10 and Ubuntu 18.04.

![123](https://user-images.githubusercontent.com/20030910/66697743-54730200-ece5-11e9-8fc3-08f5d1e70a52.png)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by hoxnox** [comment]
> this bug is still valid?

This particular issue not reproduces on 1.9.9, but now the export can suddenly hang.

For example channel https://t.me/freedom_fox - export from 1 january, hangs on "Little_Book_of_Critical..." (5295/5733).

**Comment by hoxnox** [comment]
I've tried to examine stack traces, but don't see anything usefull:
```
Thread 16 (Thread 0x7fbfadffb700 (LWP 22614)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf500b6a20, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 15 (Thread 0x7fbfacff9700 (LWP 20406)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf80002ec0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7fbfad7fa700 (LWP 20250)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf8c038440, nfds=3, timeout=533) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7fbf6cabf700 (LWP 20239)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf600028c0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7fbf6d2c0700 (LWP 20233)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf68001830, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7fbfaeffd700 (LWP 20222)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf840a6c50, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf702b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fbfaffff700 (LWP 20217)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf9c0029e0, nfds=1, timeout=9990) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fbfb5bc2700 (LWP 20215)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbf98003600, nfds=2, timeout=998) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fbfb63c3700 (LWP 20213)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfa40025e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fbfb6bc4700 (LWP 20212)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfa00029e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fbfb73c5700 (LWP 20211)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfa80029e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fbfb7bc6700 (LWP 20210)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfb000bf90, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd2329517 in ?? () from /usr/lib64/libopenal.so.1
#2  0x00007fbfc413af82 in pa_mainloop_poll () from /usr/lib64/libpulse.so.0
#3  0x00007fbfc413b59e in pa_mainloop_iterate () from /usr/lib64/libpulse.so.0
#4  0x00007fbfc413b650 in pa_mainloop_run () from /usr/lib64/libpulse.so.0
#5  0x00007fbfd2329b6b in ?? () from /usr/lib64/libopenal.so.1
#6  0x00007fbfd21a89d0 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fbfc77fe700 (LWP 20207)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfb80025e0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2e72467 in ?? () from /usr/lib64/libQt5DBus.so.5
#7  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#8  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fbfc7fff700 (LWP 20206)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfc00029e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2a17a91 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#7  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fbfccd7b700 (LWP 20205)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x7fbfccd7ab58, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1e74ca2 in ?? () from /usr/lib64/libxcb.so.1
#2  0x00007fbfd1e7677a in xcb_wait_for_event () from /usr/lib64/libxcb.so.1
#3  0x00007fbfccecaee0 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007fbfd2a189d6 in ?? () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd52bef65 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007fbfd1f7879f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fbfcd4b3980 (LWP 20204)):
#0  0x00007fbfd1f708e9 in __GI___poll (fds=0x559517fd6ba0, nfds=4, timeout=8) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fbfd1b06b0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007fbfd1b06c2f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007fbfd2bf7010 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007fbfd2ba576b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007fbfd2bacf1e in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00005595134dedde in Core::Sandbox::start (this=0x7fff420dd290) at /home/hoxnox/devel/tdesktop/Telegram/SourceFiles/core/sandbox.cpp:143
#7  0x00005595134d04e4 in Core::Launcher::executeApplication (this=0x559517bbce50) at /home/hoxnox/devel/tdesktop/Telegram/SourceFiles/core/launcher.cpp:462
#8  0x00005595134ce4d4 in Core::Launcher::exec (this=0x559517bbce50) at /home/hoxnox/devel/tdesktop/Telegram/SourceFiles/core/launcher.cpp:278
#9  0x0000559514a90eda in main (argc=3, argv=0x7fff420dd5d8) at /home/hoxnox/devel/tdesktop/Telegram/SourceFiles/main.cpp:12
```

**Comment by hoxnox** [comment]
I have Debug version of the Telegram running, hanged on the export. There is log:
```
[2020.02.01 16:32:01] RPC Error: request 43181 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:38:45] RPC Error: request 45973 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:38:46] RPC Error: request 45976 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:38:46] RPC Error: request 45979 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:31] RPC Error: request 51743 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:31] RPC Error: request 51746 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:31] RPC Error: request 51751 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:32] RPC Error: request 51754 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:35] RPC Error: request 51774 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:35] RPC Error: request 51777 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:36] RPC Error: request 51783 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:36] RPC Error: request 51786 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:49] RPC Error: request 51851 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:54:49] RPC Error: request 51854 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:55:06] RPC Error: request 51952 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:55:06] RPC Error: request 51955 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 16:59:56] Audio Info: recreating audio device and reattaching the tracks
[2020.02.01 16:59:58] Audio Info: Closing audio playback device.
[2020.02.01 17:13:33] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 17:34:10] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 17:57:04] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 18:34:44] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 18:54:42] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 18:55:57] RPC Error: request 51957 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 19:12:04] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 19:14:42] Audio Info: recreating audio device and reattaching the tracks
[2020.02.01 19:14:43] Audio Info: Closing audio playback device.
[2020.02.01 19:50:21] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 20:09:15] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 20:56:48] RPC Error: request 51967 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 21:18:12] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 22:03:57] Config Error: Failed to parse dns response JSON, error: illegal value
[2020.02.01 22:24:21] Export Info: Panel Hide On Inactive Window.
[2020.02.01 22:24:21] Export Info: Panel Hide Requested.
[2020.02.01 22:24:21] Export Info: Panel Closed.
[2020.02.01 22:24:29] Export Info: Panel Hide On Inactive Window.
[2020.02.01 22:24:29] Export Info: Panel Hide Requested.
[2020.02.01 22:24:29] Export Info: Panel Hide On Inactive Window.
[2020.02.01 22:24:29] Export Info: Panel Hide Requested.
[2020.02.01 22:24:29] Export Info: Panel Closed.
[2020.02.01 22:24:29] Export Info: Panel Closed.
[2020.02.01 22:31:12] RPC Error: request 51998 got fail with code 400, error CHAT_ADMIN_REQUIRED
[2020.02.01 22:31:12] RPC Error: request 51999 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 22:31:13] App Info: writing encrypted user settings...
[2020.02.01 22:31:19] RPC Error: request 52005 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 22:31:22] RPC Error: request 52009 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 22:31:23] RPC Error: request 52013 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2020.02.01 22:31:24] RPC Error: request 52017 got fail with code 400, error FILE_REFERENCE_EXPIRED
```

Can I provide more information?

**Comment by Aokromes** [comment]
maybe it's server bug and client needs to ignore those files......

**Comment by S-U-M-1** [comment]
This is happening to me, 3 times, on the same file, an 8.1 MB music file, only 15% of the way into the export, even when two previous MP3s by the same artist immediately before in the chat have no problem.

**Comment by S-U-M-1** [comment]
Just tried it in a different version. Same result.

**Comment by S-U-M-1** [comment]
I reported my bug [here](https://github.com/telegramdesktop/tdesktop/issues/8036).

**Comment by afwn90cj93201nixr2e1re** [comment]
Nice meme
