### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by danger89** [telegramdesktop/tdesktop#7107]
### Steps to reproduce
1. Hard to reproduce / unknown yet?

### Expected behaviour
No crashes.

### Actual behaviour

Crashed two or three times after each other.. Now it seems to work for a bit longer than 2 seconds.

```
free(): invalid pointer
Segmentation fault (core dumped)
```

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** v1.9.9

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
[2020.01.29 22:49:54] Launched version: 1009009, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.01.29 22:49:54] Executable dir: /home/melroy/Documents/Telegram/, name: Telegram
[2020.01.29 22:49:54] Initial working dir: /home/melroy/
[2020.01.29 22:49:54] Working dir: /home/melroy/.local/share/TelegramDesktop/
[2020.01.29 22:49:54] Command line: /home/melroy/Documents/Telegram/Telegram -- %u -vvv
[2020.01.29 22:49:54] Executable path before check: /home/melroy/Documents/Telegram/Telegram
[2020.01.29 22:49:54] Logs started
[2020.01.29 22:49:54] Fontconfig version: 2.12.6.
[2020.01.29 22:49:54] Connecting local socket to /run/user/1000/885ba8cb1bf4da343e453daefd1c347a-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.01.29 22:49:54] Socket connect error 0, starting server and app...
[2020.01.29 22:49:54] Moved logging from '/home/melroy/.local/share/TelegramDesktop/log_start0.txt' to '/home/melroy/.local/share/TelegramDesktop/log.txt'!
[2020.01.29 22:49:54] Opened '/home/melroy/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2020.01.29 22:49:54] Primary screen DPI: 96.1263
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
[2020.01.29 22:49:54] Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.01.29 22:49:54] Could not load 'ayatana-appindicator3' with version 1 :(
[2020.01.29 22:49:54] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2020.01.29 22:49:54] Getting DE, XDG_CURRENT_DESKTOP: 'XFCE'
[2020.01.29 22:49:54] Getting DE, DESKTOP_SESSION: 'xfce'
[2020.01.29 22:49:54] Getting DE, KDE_SESSION_VERSION: ''
[2020.01.29 22:49:54] Getting DE, GNOME_DESKTOP_SESSION_ID: ''
[2020.01.29 22:49:54] Getting DE, KDE_FULL_SESSION: ''
[2020.01.29 22:49:54] DE: Other
[2020.01.29 22:49:54] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2020.01.29 22:49:54] App Info: reading settings...
[2020.01.29 22:49:54] App Info: reading encrypted settings...
[2020.01.29 22:49:55] Lang Info: Loaded cached, keys: 2579
[2020.01.29 22:49:55] OpenAL Logging Level: (not set)
[2020.01.29 22:49:55] Audio Playback Devices: OpenAL Soft
[2020.01.29 22:49:55] Audio Playback Default Device: OpenAL Soft
[2020.01.29 22:49:55] Audio Capture Devices: Built-in Audio Analog Stereo;Monitor of Ellesmere [Radeon RX 580] Digital Stereo (HDMI 6);Monitor of Built-in Audio Analog Stereo
[2020.01.29 22:49:55] Audio Capture Default Device: Built-in Audio Analog Stereo
[2020.01.29 22:49:55] App Info: reading map...
[2020.01.29 22:49:55] App Info: reading encrypted map...
[2020.01.29 22:49:55] App Info: reading encrypted user settings...
[2020.01.29 22:49:55] App Info: encrypted user settings read.
[2020.01.29 22:49:55] App Info: reading encrypted mtp data...
[2020.01.29 22:49:55] MTP Info: read keys, current: 5, to destroy: 0
[2020.01.29 22:49:55] Map read time: 3
[2020.01.29 22:49:55] TCP Error: network - Network unreachable
[2020.01.29 22:49:55] HTTP Error: network error 99 - Network unreachable
[2020.01.29 22:49:55] Export Info: Destroy top bar by controller removal.
[2020.01.29 22:49:55] Using Qt tray icon.
[2020.01.29 22:49:55] Tray Icon: Using Qt tray icon, available: [TRUE]
[2020.01.29 22:49:55] Not using Unity Launcher count.
</details>

**Comment by Aokromes** [comment]
can you try to run it with gdb or valgrind?

**Comment by danger89** [comment]
![image](https://user-images.githubusercontent.com/628926/73401216-ff3a1b00-42ea-11ea-91c3-93088a6b2782.png)

OK now it gets irri.

gdb I do not have debug targets,.. you think it will work?

**Comment by danger89** [comment]
You are definitely writing/reading in invalid memory. Try to run some static analysis for sure.

**Comment by ronlaws86** [comment]
[strace_Telegram.log](https://github.com/telegramdesktop/tdesktop/files/4132786/strace_Telegram.log)
[gdb_telegram.log](https://github.com/telegramdesktop/tdesktop/files/4132803/gdb_telegram.log)

**Comment by yulayula16** [comment]
I think I may be experiencing this issue too on Beta 1.9.9 for Linux.

Crash seemed to occur immediately when I begin to type a message in a group chat, Telegram unexpectedly crashes. I reopened Telegram immediately after and tried typing my message again only for it to do the same once again. Not sure if it has something to do with how fast words are being typed into Telegram that triggers the crash, but it seems to happen each time when typing quickly I have noticed. My average typing speed is about 16-32 WPM, just thought it be of something to take note of just in case.

**Comment by Aokromes** [comment]
plz on crash click send crash and post id here, if you don't get send crash dialog and you can reproduce issue plz run telegram under gdb or valgrind.

**Comment by Aokromes** [comment]
@ronlaws86 your crash looks to be the same as https://github.com/telegramdesktop/tdesktop/issues/7095

**Comment by danger89** [comment]
OK.. are you awake now?

**Comment by danger89** [comment]
gdb....

```
[New Thread 0x7fffbcdbe700 (LWP 10889)]
[New Thread 0x7fffabfff700 (LWP 10890)]
[New Thread 0x7fffab7fe700 (LWP 10891)]
[Thread 0x7fffab7fe700 (LWP 10891) exited]
[New Thread 0x7fffab7fe700 (LWP 10892)]
[New Thread 0x7fffa9ffb700 (LWP 10893)]
[New Thread 0x7fffa97fa700 (LWP 10894)]
[New Thread 0x7fff97fff700 (LWP 10895)]
[Thread 0x7fffa97fa700 (LWP 10894) exited]
[Thread 0x7fff97fff700 (LWP 10895) exited]
[Thread 0x7fffa9ffb700 (LWP 10893) exited]
[New Thread 0x7fffa9ffb700 (LWP 10896)]

Thread 12 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcc866700 (LWP 10883)]
tcache_get (tc_idx=0) at malloc.c:2943
2943	malloc.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff61d4207 in tcache_get (tc_idx=0) at malloc.c:2943
#1  0x00007ffff61d4207 in __GI___libc_malloc (bytes=6) at malloc.c:3050
#2  0x00007ffff6fcd4e0 in g_ucs4_to_utf8 () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6fcf664 in g_utf8_normalize () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffaadf81a1 in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#5  0x00007fffaadf91ac in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#6  0x00007fffaadf9444 in enchant_pwl_check () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#7  0x00007fffaadf51c1 in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#8  0x00007fffaadf5fee in enchant_dict_check () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#9  0x0000000001020b1a in enchant::Dict::check(std::string const&) ()
#10 0x0000000006340580 in  ()
#11 0x00007fffb4004600 in  ()
#12 0x0000000001020e44 in  ()
#13 0x0000000000000001 in  ()
#14 0x00007fffcc865b08 in  ()
#15 0x00007fffcc865b28 in  ()
#16 0x00007fffe0029870 in  ()
#17 0x00007fffb8005148 in  ()
#18 0x00007fffb8005148 in  ()
#19 0x0000000000fc4e40 in  ()
#20 0x0000000007622700 in  ()
#21 0x00007fffcc865b00 in  ()
#22 0x00007fffcc865ae8 in  ()
#23 0x00007fffcc865bb8 in  ()
#24 0x0000000500000000 in  ()
#25 0x00007fffcc865c20 in  ()
#26 0x00007fffcc865bb8 in  ()
#27 0x00007fffcc865bc0 in  ()
---Type <return> to continue, or q <return> to quit---
```

**Comment by danger89** [comment]
```
(gdb) backtrace full
#0  0x00007ffff61d4207 in tcache_get (tc_idx=0) at malloc.c:2943
        e = 0x10e0
        ar_ptr = <optimized out>
        victim = <optimized out>
        hook = <optimized out>
        tbytes = <optimized out>
        tc_idx = <optimized out>
#1  0x00007ffff61d4207 in __GI___libc_malloc (bytes=6) at malloc.c:3050
        ar_ptr = <optimized out>
        victim = <optimized out>
        hook = <optimized out>
        tbytes = <optimized out>
        tc_idx = <optimized out>
#2  0x00007ffff6fcd4e0 in g_ucs4_to_utf8 () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6fcf664 in g_utf8_normalize () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffaadf81a1 in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#5  0x00007fffaadf91ac in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#6  0x00007fffaadf9444 in enchant_pwl_check () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#7  0x00007fffaadf51c1 in  () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#8  0x00007fffaadf5fee in enchant_dict_check () at /usr/lib/x86_64-linux-gnu/libenchant.so.1
#9  0x0000000001020b1a in enchant::Dict::check(std::string const&) ()
#10 0x0000000006340580 in  ()
#11 0x00007fffb4004600 in  ()
#12 0x0000000001020e44 in  ()
#13 0x0000000000000001 in  ()
#14 0x00007fffcc865b08 in  ()
#15 0x00007fffcc865b28 in  ()
#16 0x00007fffe0029870 in  ()
```

**Comment by danger89** [comment]
```
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fca800 (LWP 10858) "Telegram" 0x00007ffff6251bf9 in __GI___poll (fds=0x68959d0, nfds=5, 
    timeout=8) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7ffff49d5700 (LWP 10868) "QXcbEventQueue" 0x00007ffff6251bf9 in __GI___poll (fds=0x7ffff49d4cb8, 
    nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  3    Thread 0x7fffef9e5700 (LWP 10869) "QThread" 0x00007ffff6251bf9 in __GI___poll (fds=0x7fffe8004db0, nfds=1, 
    timeout=894997) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7fffef1e4700 (LWP 10875) "QDBusConnection" 0x00007ffff6251bf9 in __GI___poll (fds=0x7fffe00266b0, 
    nfds=7, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7fffee9e3700 (LWP 10876) "Qt bearer threa" 0x00007ffff6251bf9 in __GI___poll (fds=0x7fffe4003ce0, 
    nfds=1, timeout=9639) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7fffed19f700 (LWP 10878) "Thread (pooled)" 0x00007ffff6af1ed9 in futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7fffed19ec50, expected=0, futex_word=0x7fffd80065a0)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:142
  8    Thread 0x7fffed9a0700 (LWP 10879) "Thread (pooled)" 0x00007ffff6af1ed9 in futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7fffed99fc50, expected=0, futex_word=0x6db2770)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:142
  9    Thread 0x7fffce247700 (LWP 10880) "Thread (pooled)" 0x00007ffff6af1ed9 in futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7fffce246c50, expected=0, futex_word=0x6dae820)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:142
  10   Thread 0x7fffcd9a3700 (LWP 10881) "Thread (pooled)" 0x00007ffff6af1ed9 in futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7fffcd9a2c50, expected=0, futex_word=0x6daee54)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:142
  11   Thread 0x7fffcd0ff700 (LWP 10882) "Thread (pooled)" 0x00007ffff6af1ed9 in futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7fffcd0fec50, expected=0, futex_word=0x6daf4b4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:142
* 12   Thread 0x7fffcc866700 (LWP 10883) "Thread (pooled)" tcache_get (tc_idx=0) at malloc.c:2943
  13   Thread 0x7fffbfede700 (LWP 10884) "Thread (pooled)" 0x00007ffff61d13c1 in _int_malloc (
```

**Comment by danger89** [comment]
```
(gdb) disassemble
Dump of assembler code for function __GI___libc_malloc:
   0x00007ffff61d4070 <+0>:	push   %rbp
   0x00007ffff61d4071 <+1>:	push   %rbx
   0x00007ffff61d4072 <+2>:	sub    $0x18,%rsp
   0x00007ffff61d4076 <+6>:	mov    0x353e63(%rip),%rax        # 0x7ffff6527ee0
   0x00007ffff61d407d <+13>:	mov    (%rax),%rax
   0x00007ffff61d4080 <+16>:	test   %rax,%rax
   0x00007ffff61d4083 <+19>:	jne    0x7ffff61d4270 <__GI___libc_malloc+512>
   0x00007ffff61d4089 <+25>:	lea    0x17(%rdi),%rax
   0x00007ffff61d408d <+29>:	cmp    $0x1f,%rax
   0x00007ffff61d4091 <+33>:	ja     0x7ffff61d41a0 <__GI___libc_malloc+304>
   0x00007ffff61d4097 <+39>:	xor    %edx,%edx
   0x00007ffff61d4099 <+41>:	mov    $0x20,%eax
   0x00007ffff61d409e <+46>:	cmp    %rdi,%rax
   0x00007ffff61d40a1 <+49>:	jb     0x7ffff61d4280 <__GI___libc_malloc+528>
   0x00007ffff61d40a7 <+55>:	test   %dl,%dl
   0x00007ffff61d40a9 <+57>:	jne    0x7ffff61d4280 <__GI___libc_malloc+528>
   0x00007ffff61d40af <+63>:	mov    0x353cc2(%rip),%rbp        # 0x7ffff6527d78
   0x00007ffff61d40b6 <+70>:	sub    $0x11,%rax
   0x00007ffff61d40ba <+74>:	mov    %rdi,%rbx
   0x00007ffff61d40bd <+77>:	shr    $0x4,%rax
   0x00007ffff61d40c1 <+81>:	mov    %fs:0x0(%rbp),%rcx
   0x00007ffff61d40c6 <+86>:	test   %rcx,%rcx
   0x00007ffff61d40c9 <+89>:	je     0x7ffff61d41b0 <__GI___libc_malloc+320>
   0x00007ffff61d40cf <+95>:	cmp    0x3541fa(%rip),%rax        # 0x7ffff65282d0 <mp_+80>
   0x00007ffff61d40d6 <+102>:	jb     0x7ffff61d41f0 <__GI___libc_malloc+384>
   0x00007ffff61d40dc <+108>:	lea    0x359815(%rip),%rax        # 0x7ffff652d8f8 <__libc_multiple_threads>
   0x00007ffff61d40e3 <+115>:	mov    (%rax),%eax
```

Now I stopped.. Since I do not know if I need to continue/add a break somewhere/what you want me to do.

**Comment by Aokromes** [comment]
yeah it's #7095
