### ISSUE TITLE
build error : failed with error 255

### ISSUE THREAD

**Issue by opksha** [telegramdesktop/tdesktop#7405]
### Steps to reproduce
1. 
follow this link:

[building-msvc.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#install-third-party-software)

### Expected behaviour
no error messages appear

### Actual behaviour

- env
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.6
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
```
- error
```
C:\Users\user123\Desktop\git\buildpath\Libraries\breakpad\src\client\windows>gyp --no-circular-check breakpad_client.gyp --format=ninja
Traceback (most recent call last):
  File "C:\Users\user123\Desktop\git\buildpath\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\user123\Desktop\git\buildpath\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "C:\Users\user123\Desktop\git\buildpath\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "C:\Users\user123\Desktop\git\buildpath\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\user123\Desktop\git\buildpath\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2493, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Python2716\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python2716\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
Exception: "['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
```

### Configuration
**Operating system:**
windows
**Version of Telegram Desktop:**

**Comment by opksha** [comment]
resolved

**Comment by rvier** [comment]
I got the similar problem after “git submodule update”.
How did you do that
