### ISSUE TITLE
[Question] ValueError: Could not locate Visual Studio installation.

### ISSUE THREAD

**Issue by chenyu1990** [telegramdesktop/tdesktop#8195]
`E:\C++\tdesktop-2.1.13\Libraries\breakpad\src\client\windows>gyp --no-circular-check breakpad_client.gyp --format=ninja
Traceback (most recent call last):
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\__init__.py", line 521, in gyp_main
    options.duplicate_basename_check)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\__init__.py", line 105, in Load
    generator.CalculateVariables(default_variables, params)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1701, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 1101, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 952, in GetVSVersion
    allow_fallback=False)
  File "E:\C++\tdesktop-2.1.13\ThirdParty\gyp\pylib\gyp\MSVSVersion.py", line 498, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.`

Configuration
Operating system:
win10

and I install the python 2.7. and visual studio 2019.
please help me.

**Comment by chenyu1990** [comment]
`set GYP_MSVS_OVERRIDE_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community`
